#ifndef MOBILE_SDK_H
#define MOBILE_SDK_H

/* Warning: autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void rust_free_string(char *s);

int32_t run_client_c(const char *ws_url, const char *validator_private_key, char **out_error);

char *generate_bls12_381_keypair_c(char **out_error);

char *create_deposit_unsigned_tx_c(const char *deposit_contract_address,
                                   const char *validator_private_key,
                                   const char *withdrawal_address,
                                   const char *deposit_value_in_wei,
                                   char **out_error);

char *create_get_exit_fee_unsigned_tx_c(char **out_error);

char *create_exit_unsigned_tx_c(const char *validator_public_key,
                                const char *fee_in_wei_or_empty,
                                char **out_error);

#endif  /* MOBILE_SDK_H */
