import 'package:n42_wallet/src/component/enums/coin_type.dart';

final Map<String, dynamic> chainUrlConfigsPart2 = <String, dynamic>{
  CoinType.SCROLL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SCROLL",
      "icon": "https://cryptologos.cc/logos/scroll-scr-logo.png",
      "name": "Scroll",
      "miniName": "SCROLL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SCROLL",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.scroll.io",
      "service_test": "",
      "chainId": 534352,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 534352,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MNT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MNT",
      "icon": "https://cryptologos.cc/logos/mantle-mnt-logo.png",
      "name": "Mantle",
      "miniName": "MNT",
      "unit": "MNT",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MNT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mantle.xyz",
      "service_test": "",
      "chainId": 5000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 5000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BLAST.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BLAST",
      "icon": "https://cryptologos.cc/logos/blast-blast-logo.png",
      "name": "Blast",
      "miniName": "BLAST",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BLAST",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.blast.io",
      "service_test": "",
      "chainId": 81457,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 81457,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NOVA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "NOVA",
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum Nova",
      "miniName": "NOVA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NOVA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://nova.arbitrum.io/rpc",
      "service_test": "",
      "chainId": 42170,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42170,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 2: Other Mainstream L1/L2 ============
  CoinType.CRO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CRO",
      "icon": "https://cryptologos.cc/logos/cronos-cro-logo.png",
      "name": "Cronos",
      "miniName": "CRO",
      "unit": "CRO",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CRO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.cronos.org",
      "service_test": "",
      "chainId": 25,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 25,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GNOSIS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GNOSIS",
      "icon": "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png",
      "name": "Gnosis Chain",
      "miniName": "xDAI",
      "unit": "xDAI",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GNOSIS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gnosischain.com",
      "service_test": "",
      "chainId": 100,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 100,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.AURORA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "AURORA",
      "icon": "https://cryptologos.cc/logos/aurora-aurora-logo.png",
      "name": "Aurora",
      "miniName": "AURORA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "AURORA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.aurora.dev",
      "service_test": "",
      "chainId": 1313161554,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1313161554,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FUSE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FUSE",
      "icon": "https://cryptologos.cc/logos/fuse-fuse-logo.png",
      "name": "Fuse",
      "miniName": "FUSE",
      "unit": "FUSE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FUSE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.fuse.io",
      "service_test": "",
      "chainId": 122,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 122,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZKPOLYGON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKPOLYGON",
      "icon": "https://cryptologos.cc/logos/polygon-matic-logo.png",
      "name": "Polygon zkEVM",
      "miniName": "zkPOL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKPOLYGON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://zkevm-rpc.com",
      "service_test": "",
      "chainId": 1101,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1101,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MODE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MODE",
      "icon": "https://cryptologos.cc/logos/mode-mode-logo.png",
      "name": "Mode",
      "miniName": "MODE",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MODE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.mode.network",
      "service_test": "",
      "chainId": 34443,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 34443,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MANTA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MANTA",
      "icon": "https://cryptologos.cc/logos/manta-network-manta-logo.png",
      "name": "Manta Pacific",
      "miniName": "MANTA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MANTA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://pacific-rpc.manta.network/http",
      "service_test": "",
      "chainId": 169,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 169,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CANTO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CANTO",
      "icon": "https://cryptologos.cc/logos/canto-canto-logo.png",
      "name": "Canto",
      "miniName": "CANTO",
      "unit": "CANTO",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CANTO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://canto.slingshot.finance",
      "service_test": "",
      "chainId": 7700,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7700,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KAVA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KAVA",
      "icon": "https://cryptologos.cc/logos/kava-kava-logo.png",
      "name": "Kava EVM",
      "miniName": "KAVA",
      "unit": "KAVA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KAVA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.kava.io",
      "service_test": "",
      "chainId": 2222,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2222,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ROSE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ROSE",
      "icon": "https://cryptologos.cc/logos/oasis-network-rose-logo.png",
      "name": "Oasis Emerald",
      "miniName": "ROSE",
      "unit": "ROSE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ROSE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://emerald.oasis.dev",
      "service_test": "",
      "chainId": 42262,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42262,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 3: Gaming/NFT/Ecosystem Chains ============
  CoinType.RON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "RON",
      "icon": "https://cryptologos.cc/logos/ronin-ron-logo.png",
      "name": "Ronin",
      "miniName": "RON",
      "unit": "RON",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.roninchain.com",
      "service_test": "",
      "chainId": 2020,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2020,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.IMX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IMX",
      "icon": "https://cryptologos.cc/logos/immutable-imx-logo.png",
      "name": "Immutable zkEVM",
      "miniName": "IMX",
      "unit": "IMX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IMX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.immutable.com",
      "service_test": "",
      "chainId": 13371,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 13371,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.APE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "APE",
      "icon": "https://cryptologos.cc/logos/apecoin-ape-logo.png",
      "name": "ApeChain",
      "miniName": "APE",
      "unit": "APE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "APE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.apechain.com/http",
      "service_test": "",
      "chainId": 33139,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 33139,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BONE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BONE",
      "icon": "https://cryptologos.cc/logos/shiba-inu-shib-logo.png",
      "name": "Shibarium",
      "miniName": "BONE",
      "unit": "BONE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BONE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://www.shibrpc.com",
      "service_test": "",
      "chainId": 109,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 109,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CHZ.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CHZ",
      "icon": "https://cryptologos.cc/logos/chiliz-chz-logo.png",
      "name": "Chiliz Chain",
      "miniName": "CHZ",
      "unit": "CHZ",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CHZ",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.ankr.com/chiliz",
      "service_test": "",
      "chainId": 88888,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 88888,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DOGECHAIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "DOGECHAIN",
      "icon": "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
      "name": "Dogechain",
      "miniName": "DC",
      "unit": "DOGE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DOGECHAIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.dogechain.dog",
      "service_test": "",
      "chainId": 2000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WLD.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WLD",
      "icon": "https://cryptologos.cc/logos/worldcoin-wld-logo.png",
      "name": "World Chain",
      "miniName": "WLD",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WLD",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://worldchain-mainnet.g.alchemy.com/public",
      "service_test": "",
      "chainId": 480,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 480,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 4: Bitcoin L2 Chains ============
  CoinType.RBTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "RBTC",
      "icon": "https://cryptologos.cc/logos/rsk-infrastructure-framework-rif-logo.png",
      "name": "Rootstock",
      "miniName": "RBTC",
      "unit": "RBTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RBTC",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://public-node.rsk.co",
      "service_test": "",
      "chainId": 30,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 30,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MERLIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MERLIN",
      "icon": "https://cryptologos.cc/logos/merlin-chain-merl-logo.png",
      "name": "Merlin Chain",
      "miniName": "MERL",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MERLIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.merlinchain.io",
      "service_test": "",
      "chainId": 4200,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 4200,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CORE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CORE",
      "icon": "https://cryptologos.cc/logos/core-dao-core-logo.png",
      "name": "Core DAO",
      "miniName": "CORE",
      "unit": "CORE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CORE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.coredao.org",
      "service_test": "",
      "chainId": 1116,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1116,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BEVM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BEVM",
      "icon": "https://www.n42.ai/static/bevm.png",
      "name": "BEVM",
      "miniName": "BEVM",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BEVM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc-mainnet-1.bevm.io",
      "service_test": "",
      "chainId": 11501,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 11501,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 5: New L1/L2 Chains ============
  CoinType.BERA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BERA",
      "icon": "https://cryptologos.cc/logos/berachain-bera-logo.png",
      "name": "Berachain",
      "miniName": "BERA",
      "unit": "BERA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BERA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.berachain.com",
      "service_test": "",
      "chainId": 80094,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 80094,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SEI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SEI",
      "icon": "https://cryptologos.cc/logos/sei-sei-logo.png",
      "name": "Sei",
      "miniName": "SEI",
      "unit": "SEI",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SEI",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm-rpc.sei-apis.com",
      "service_test": "",
      "chainId": 1329,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1329,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.PLS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "PLS",
      "icon": "https://cryptologos.cc/logos/pulsechain-pls-logo.png",
      "name": "PulseChain",
      "miniName": "PLS",
      "unit": "PLS",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "PLS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.pulsechain.com",
      "service_test": "",
      "chainId": 369,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 369,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HBAR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HBAR",
      "icon": "https://cryptologos.cc/logos/hedera-hbar-logo.png",
      "name": "Hedera",
      "miniName": "HBAR",
      "unit": "HBAR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HBAR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.hashio.io/api",
      "service_test": "",
      "chainId": 295,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 295,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FLR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FLR",
      "icon": "https://cryptologos.cc/logos/flare-flr-logo.png",
      "name": "Flare",
      "miniName": "FLR",
      "unit": "FLR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FLR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://flare-api.flare.network/ext/C/rpc",
      "service_test": "",
      "chainId": 14,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 14,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SGB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SGB",
      "icon": "https://cryptologos.cc/logos/songbird-sgb-logo.png",
      "name": "Songbird",
      "miniName": "SGB",
      "unit": "SGB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SGB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://songbird-api.flare.network/ext/C/rpc",
      "service_test": "",
      "chainId": 19,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 19,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 6: Other EVM Chains ============
  CoinType.CFX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CFX",
      "icon": "https://cryptologos.cc/logos/conflux-network-cfx-logo.png",
      "name": "Conflux eSpace",
      "miniName": "CFX",
      "unit": "CFX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CFX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.confluxrpc.com",
      "service_test": "",
      "chainId": 1030,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1030,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TLOS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TLOS",
      "icon": "https://cryptologos.cc/logos/telos-tlos-logo.png",
      "name": "Telos EVM",
      "miniName": "TLOS",
      "unit": "TLOS",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TLOS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.telos.net/evm",
      "service_test": "",
      "chainId": 40,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 40,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ASTR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ASTR",
      "icon": "https://cryptologos.cc/logos/astar-astr-logo.png",
      "name": "Astar EVM",
      "miniName": "ASTR",
      "unit": "ASTR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ASTR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.astar.network",
      "service_test": "",
      "chainId": 592,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 592,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BTT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BTT",
      "icon": "https://cryptologos.cc/logos/bittorrent-btt-logo.png",
      "name": "BitTorrent Chain",
      "miniName": "BTT",
      "unit": "BTT",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BTT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.bittorrentchain.io",
      "service_test": "",
      "chainId": 199,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 199,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZORA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZORA",
      "icon": "https://cryptologos.cc/logos/zora-zora-logo.png",
      "name": "Zora",
      "miniName": "ZORA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZORA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.zora.energy",
      "service_test": "",
      "chainId": 7777777,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7777777,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TAIKO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TAIKO",
      "icon": "https://cryptologos.cc/logos/taiko-taiko-logo.png",
      "name": "Taiko",
      "miniName": "TAIKO",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TAIKO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mainnet.taiko.xyz",
      "service_test": "",
      "chainId": 167000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 167000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OPBNB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OPBNB",
      "icon": "https://cryptologos.cc/logos/bnb-bnb-logo.png",
      "name": "opBNB",
      "miniName": "opBNB",
      "unit": "BNB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OPBNB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://opbnb-mainnet-rpc.bnbchain.org",
      "service_test": "",
      "chainId": 204,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 204,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FRAX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FRAX",
      "icon": "https://cryptologos.cc/logos/frax-frax-logo.png",
      "name": "Fraxtal",
      "miniName": "FRAX",
      "unit": "frxETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FRAX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.frax.com",
      "service_test": "",
      "chainId": 252,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 252,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 7: Additional EVM Chains ============
  CoinType.SDN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SDN",
      "icon": "https://cryptologos.cc/logos/shiden-sdn-logo.png",
      "name": "Shiden",
      "miniName": "SDN",
      "unit": "SDN",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SDN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://shiden.api.onfinality.io/public",
      "service_test": "",
      "chainId": 336,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 336,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
