N42_CHAT_GOOGLE_CLIENT_ID=
N42_CHAT_GOOGLE_SERVER_CLIENT_ID=
N42_CHAT_TWITTER_API_KEY=
N42_CHAT_TWITTER_API_SECRET=
N42_CHAT_TWITTER_REDIRECT_URI=n42://auth/twitter
N42_CHAT_WECHAT_APP_ID=
N42_CHAT_WECHAT_UNIVERSAL_LINK=
