name: fl_chart
description: A highly customizable Flutter chart library that supports Line Chart, Bar Chart, Pie Chart, Scatter Chart, and Radar Chart.
version: 1.2.0
homepage: https://flchart.dev/
repository: https://github.com/imaNNeo/fl_chart
issue_tracker: https://github.com/imaNNeo/fl_chart/issues
documentation: https://github.com/imaNNeo/fl_chart

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.27.4"

funding:
  - https://github.com/sponsors/imaNNeo
  - https://www.buymeacoffee.com/fl_chart

dependencies:
  equatable: ^3.0.0
  flutter:
    sdk: flutter
  vector_math: ^2.2.0
