import 'package:n42_wallet/features/component/enums/coin_type.dart';

final Map<String, dynamic> chainUrlConfigsPart3 = <String, dynamic>{
  CoinType.ACA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ACA",
      "icon": "https://cryptologos.cc/logos/acala-aca-logo.png",
      "name": "Acala EVM+",
      "miniName": "ACA",
      "unit": "ACA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ACA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://eth-rpc-acala.aca-api.network",
      "service_test": "",
      "chainId": 787,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 787,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BNC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BNC",
      "icon": "https://cryptologos.cc/logos/bifrost-bnc-logo.png",
      "name": "Bifrost",
      "miniName": "BNC",
      "unit": "BNC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BNC",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://hk.p.bifrost.app/rpc",
      "service_test": "",
      "chainId": 996,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 996,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.VIC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "VIC",
      "icon": "https://cryptologos.cc/logos/viction-vic-logo.png",
      "name": "Viction",
      "miniName": "VIC",
      "unit": "VIC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "VIC",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.viction.xyz",
      "service_test": "",
      "chainId": 88,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 88,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FSN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FSN",
      "icon": "https://cryptologos.cc/logos/fusion-fsn-logo.png",
      "name": "Fusion",
      "miniName": "FSN",
      "unit": "FSN",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FSN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.fusionnetwork.io",
      "service_test": "",
      "chainId": 32659,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 32659,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.EWT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "EWT",
      "icon": "https://cryptologos.cc/logos/energy-web-token-ewt-logo.png",
      "name": "Energy Web",
      "miniName": "EWT",
      "unit": "EWT",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EWT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.energyweb.org",
      "service_test": "",
      "chainId": 246,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 246,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BRISE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BRISE",
      "icon": "https://cryptologos.cc/logos/bitgert-brise-logo.png",
      "name": "Bitgert",
      "miniName": "BRISE",
      "unit": "BRISE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BRISE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.icecreamswap.com",
      "service_test": "",
      "chainId": 32520,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 32520,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.REEF.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "REEF",
      "icon": "https://cryptologos.cc/logos/reef-reef-logo.png",
      "name": "Reef Chain",
      "miniName": "REEF",
      "unit": "REEF",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "REEF",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.reefscan.com",
      "service_test": "",
      "chainId": 13939,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 13939,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FX",
      "icon": "https://cryptologos.cc/logos/function-x-fx-logo.png",
      "name": "Function X",
      "miniName": "FX",
      "unit": "FX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://fx-json-web3.functionx.io:8545",
      "service_test": "",
      "chainId": 530,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 530,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ISLM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ISLM",
      "icon": "https://cryptologos.cc/logos/haqq-network-islm-logo.png",
      "name": "HAQQ Network",
      "miniName": "ISLM",
      "unit": "ISLM",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ISLM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.eth.haqq.network",
      "service_test": "",
      "chainId": 11235,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 11235,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NEON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "NEON",
      "icon": "https://cryptologos.cc/logos/neon-neon-logo.png",
      "name": "Neon EVM",
      "miniName": "NEON",
      "unit": "NEON",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NEON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://neon-proxy-mainnet.solana.p2p.org",
      "service_test": "",
      "chainId": 245022934,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 245022934,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SYS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SYS",
      "icon": "https://cryptologos.cc/logos/syscoin-sys-logo.png",
      "name": "Syscoin NEVM",
      "miniName": "SYS",
      "unit": "SYS",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SYS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.syscoin.org",
      "service_test": "",
      "chainId": 57,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 57,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ELA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ELA",
      "icon": "https://cryptologos.cc/logos/elastos-ela-logo.png",
      "name": "Elastos Smart Chain",
      "miniName": "ELA",
      "unit": "ELA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ELA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.elastos.io/esc",
      "service_test": "",
      "chainId": 20,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 20,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZIRCUIT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZIRCUIT",
      "icon": "https://www.n42.ai/static/zircuit.png",
      "name": "Zircuit",
      "miniName": "ZRC",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZIRCUIT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://zircuit1-mainnet.p2pify.com",
      "service_test": "",
      "chainId": 48900,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 48900,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KROMA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KROMA",
      "icon": "https://www.n42.ai/static/kroma.png",
      "name": "Kroma",
      "miniName": "KRO",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KROMA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.kroma.network",
      "service_test": "",
      "chainId": 255,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 255,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LISK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "LISK",
      "icon": "https://cryptologos.cc/logos/lisk-lsk-logo.png",
      "name": "Lisk",
      "miniName": "LSK",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LISK",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.api.lisk.com",
      "service_test": "",
      "chainId": 1135,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1135,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.UNICHAIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "UNICHAIN",
      "icon": "https://cryptologos.cc/logos/uniswap-uni-logo.png",
      "name": "Unichain",
      "miniName": "UNI",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "UNICHAIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.unichain.org",
      "service_test": "",
      "chainId": 130,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 130,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.INK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "INK",
      "icon": "https://www.n42.ai/static/ink.png",
      "name": "Ink",
      "miniName": "INK",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "INK",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc-gel.inkonchain.com",
      "service_test": "",
      "chainId": 57073,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 57073,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BITLAYER.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BITLAYER",
      "icon": "https://www.n42.ai/static/bitlayer.png",
      "name": "Bitlayer",
      "miniName": "BTR",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BITLAYER",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.bitlayer.org",
      "service_test": "",
      "chainId": 200901,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 200901,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZKLINK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKLINK",
      "icon": "https://www.n42.ai/static/zklink.png",
      "name": "zkLink Nova",
      "miniName": "ZKL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKLINK",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.zklink.io",
      "service_test": "",
      "chainId": 810180,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 810180,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CYBER.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CYBER",
      "icon": "https://www.n42.ai/static/cyber.png",
      "name": "Cyber",
      "miniName": "CYBER",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CYBER",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://cyber.alt.technology",
      "service_test": "",
      "chainId": 7560,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7560,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MINT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MINT",
      "icon": "https://www.n42.ai/static/mint.png",
      "name": "Mint",
      "miniName": "MINT",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MINT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mintchain.io",
      "service_test": "",
      "chainId": 185,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 185,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GRAVITY.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GRAVITY",
      "icon": "https://www.n42.ai/static/gravity.png",
      "name": "Gravity",
      "miniName": "G",
      "unit": "G",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GRAVITY",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gravity.xyz",
      "service_test": "",
      "chainId": 1625,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1625,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HEMI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HEMI",
      "icon": "https://www.n42.ai/static/hemi.png",
      "name": "Hemi",
      "miniName": "HEMI",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HEMI",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.hemi.network/rpc",
      "service_test": "",
      "chainId": 43111,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 43111,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HSK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HSK",
      "icon": "https://www.n42.ai/static/hashkey.png",
      "name": "HashKey Chain",
      "miniName": "HSK",
      "unit": "HSK",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HSK",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.hsk.xyz",
      "service_test": "",
      "chainId": 177,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 177,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SWAN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SWAN",
      "icon": "https://www.n42.ai/static/swan.png",
      "name": "Swan Chain",
      "miniName": "SWAN",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SWAN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet-rpc.swanchain.org",
      "service_test": "",
      "chainId": 254,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 254,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XLAYER.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "XLAYER",
      "icon": "https://www.n42.ai/static/xlayer.png",
      "name": "X Layer",
      "miniName": "OKB",
      "unit": "OKB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XLAYER",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.xlayer.tech",
      "service_test": "",
      "chainId": 196,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 196,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZKFAIR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKFAIR",
      "icon": "https://www.n42.ai/static/zkfair.png",
      "name": "zkFair",
      "miniName": "ZKF",
      "unit": "USDC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKFAIR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.zkfair.io",
      "service_test": "",
      "chainId": 42766,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42766,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BOBAETH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BOBAETH",
      "icon": "https://www.n42.ai/static/bob.png",
      "name": "BOB",
      "miniName": "BOB",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BOBAETH",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gobob.xyz",
      "service_test": "",
      "chainId": 60808,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 60808,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.REDSTONE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "REDSTONE",
      "icon": "https://www.n42.ai/static/redstone.png",
      "name": "Redstone",
      "miniName": "RED",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "REDSTONE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.redstonechain.com",
      "service_test": "",
      "chainId": 690,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 690,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MILKOMEDA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MILKOMEDA",
      "icon": "https://www.n42.ai/static/milkomeda.png",
      "name": "Milkomeda C1",
      "miniName": "milkADA",
      "unit": "milkADA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MILKOMEDA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc-mainnet-cardano-evm.c1.milkomeda.com",
      "service_test": "",
      "chainId": 2001,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2001,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Batch 8: Remaining EVM chains
  CoinType.BB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BB",
      "icon": "https://cryptologos.cc/logos/bouncebit-bb-logo.png",
      "name": "BounceBit",
      "miniName": "BB",
      "unit": "BB",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://fullnode-mainnet.bouncebitapi.com",
      "service_test": "",
      "chainId": 6001,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 6001,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BOBBNB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BOBBNB",
      "icon": "https://cryptologos.cc/logos/boba-network-boba-logo.png",
      "name": "Boba BNB",
      "miniName": "BOBA",
      "unit": "BOBA",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BOBBNB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://bnb.boba.network",
      "service_test": "",
      "chainId": 56288,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 56288,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CLO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CLO",
      "icon": "https://cryptologos.cc/logos/callisto-network-clo-logo.png",
      "name": "Callisto Network",
      "miniName": "CLO",
      "unit": "CLO",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CLO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.callisto.network",
      "service_test": "",
      "chainId": 820,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 820,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DYM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "DYM",
      "icon": "https://cryptologos.cc/logos/dymension-dym-logo.png",
      "name": "Dymension",
      "miniName": "DYM",
      "unit": "DYM",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DYM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://dymension-evm-rpc.publicnode.com",
      "service_test": "",
      "chainId": 1100,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1100,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.EVMOS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "EVMOS",
      "icon": "https://cryptologos.cc/logos/evmos-evmos-logo.png",
      "name": "Evmos",
      "miniName": "EVMOS",
      "unit": "EVMOS",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EVMOS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evmos-evm-rpc.publicnode.com",
      "service_test": "",
      "chainId": 9001,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 9001,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GOAT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GOAT",
      "icon": "https://cryptologos.cc/logos/goat-network-logo.png",
      "name": "GOAT Network",
      "miniName": "GOAT",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GOAT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.goat.network",
      "service_test": "",
      "chainId": 2345,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2345,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GT",
      "icon": "https://cryptologos.cc/logos/gatetoken-gt-logo.png",
      "name": "Gate Chain",
      "miniName": "GT",
      "unit": "GT",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.gatenode.cc",
      "service_test": "",
      "chainId": 86,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 86,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.METAL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "METAL",
      "icon": "https://cryptologos.cc/logos/metal-l2-logo.png",
      "name": "Metal L2",
      "miniName": "METAL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "METAL",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.metall2.com",
      "service_test": "",
      "chainId": 1750,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1750,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NUM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "NUM",
      "icon": "https://cryptologos.cc/logos/numbers-protocol-num-logo.png",
      "name": "Numbers Protocol",
      "miniName": "NUM",
      "unit": "NUM",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NUM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnetrpc.num.network",
      "service_test": "",
      "chainId": 10507,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 10507,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.PALM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "PALM",
      "icon": "https://cryptologos.cc/logos/palm-logo.png",
      "name": "Palm",
      "miniName": "PALM",
      "unit": "PALM",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "PALM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://palm-mainnet.public.blastapi.io",
      "service_test": "",
      "chainId": 11297108109,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 11297108109,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
