//walletList中使用 - Part 1: N, BTC, ETH, SOL, BNB, ARB, OP, BASE, AVAX, MATIC, TON, TRX, XRP, ATOM, DOT, FIL, SUI, APT
import 'package:n42_wallet/features/component/enums/coin_type.dart';

Map<String,dynamic> walletChainConfigsPart1={
  CoinType.N.name:<String,dynamic>{
    "showList":true,//主链币是否显示在主页列表中
    "isTest":false,//是否时正式链
    "supportTest":true,
    "addrType":"legacy",//地址类型
    "pathIndex":0,//path具体的账号节点
    "pathList":[0],//path数量
    "baseInfo":<String,dynamic>{
      "mKey": "N",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.N.name,
      "icon": "https://n42.ai/static/n42.png",
      "name": "N42",
      "miniName": "N",
      "unit":"N",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.n42.world",
      "service_test": const String.fromEnvironment('N42_TESTNET_RPC', defaultValue: 'https://testrpc.n42.world'),
      "chainId": 94,
      "chainId_test": 1142,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":94,
    "testnetChainID":1142,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"wss://testws.n42.world",
        "testnetRPC":"https://testrpc.n42.world",
        "testnetChainID":1142,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
      "erc1155":"0x7632cA0FE8CBE97a59c600e5Afb3e75B9eC3Dc05",
      "erc721":"0xD535A5DAC95E5D5C9E121E20257E71a8FED74d95",
      "Market":"0x60a073d2F24884212859B10161590d7A67e225F9",
      "NftAddress":"0x70c8A83193a23Dd49Db33996570A573960Cf7653",
    },
    "testnetContract":{
      "erc1155":"0xfd89417A8BE37e27162376b3a76E1EA2e1d930A9",
      "erc721":"0x1b035d6a285682De59f3b529e53D7D14b652014f",
      "Market":"0x958Bb3Fd435aC84302E8f3dE582730860825f00a",
      "NftAddress":"0xd02Da544Aa8F09F16c0FE28CA0C53772C95FB146",
    },
    "miningContract": "0x581231E78f9C15882ace8b6597b619999aeD5137"
  },

  // 2. BTC - Bitcoin（最知名加密货币）
  CoinType.BTC.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"segwit",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.BTC.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Bitcoin.png",
      "name": "Bitcoin",
      "miniName": "BTC",
      "unit":"BTC",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BTC",
      "path": {
        "legacy":"m/44'/0'/0'/0/0",
        "segwit":"m/84'/1'/0'/0/0",
        "taproot":"m/86'/0'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{
    },
    "testnetContract":{},
  },

  // 3. ETH - Ethereum（第二大加密货币）
  CoinType.ETH.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "mKey": "ETH",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ETH.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Ethereum.png",
      "name": "Ethereum",
      "miniName": "ETH",
      "unit":"ETH",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.infura.io/v3/", // Updated at runtime by RpcConfig.infuraApiKey
      "service_test": "https://eth-sepolia.public.blastapi.io",
      "chainId": 1,
      "chainId_test": 11155111,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":1,
    "testnetChainID":3,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://eth-sepolia.public.blastapi.io",
        "testnetRPC":"https://eth-sepolia.public.blastapi.io",
        "testnetChainID":11155111,
        "testnetContract":<String,dynamic>{
          "0X6C30A50430CC615C4659DF2DBE3E42036583BE7E":<String,dynamic>{
            "mKey": "0X6C30A50430CC615C4659DF2DBE3E42036583BE7E",
            "blockchainType": BlockchainType.Ethereum.name,
            "coinType": CoinType.ETH.name,
            "icon": "https://api.n42.ai/market/v1/r/coinImage/vbtc.png",
            "name": "vBTC",
            "miniName": "vBTC",
            "unit":"vBTC",
            "decimals": 8,
            "balance":"0",
            "balance_test":"0",
            "coinPrice":0.0,
            "percentage":0.0,
            "isContract": true,
            "path": {
              "legacy":"m/44'/60'/0'/0/0",
            },
            "service": const String.fromEnvironment('ETH_RPC_URL', defaultValue: 'https://rpc.n42.world'),
            "service_test": "https://eth-sepolia.public.blastapi.io",
            "chainId": 1,
            "chainId_test": 11155111,
            "contract": "0x6c30A50430cC615C4659DF2dBe3E42036583bE7E",
            "contract_test": "0x6c30A50430cC615C4659DF2dBe3E42036583bE7E",
            "canEdit": false,
            "rules": "ERC20",
            "customer":false,
          }
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
  },

  // 4. SOL - Solana（高性能公链，热门）
  CoinType.SOL.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Solana.name,
      "coinType": CoinType.SOL.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Solana.png",
      "name": "Solana",
      "miniName": "SOL",
      "unit":"SOL",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SOL",
      "path": {
        "legacy":"m/44'/501'/0'",
      },
      "service": "https://api.mainnet-beta.solana.com",
      "service_test": "https://api.testnet.solana.com",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "SPL",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
      "SOL":"7ViD4q77VfADUiE2euhBVmrvYrrMJW3bFbjcgvujmAyZ",
    },
  },

  // 5. BNB - Binance Smart Chain（交易所生态，热门）
  CoinType.BNB.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BNB.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/BNB.png",
      "name": "Binance Smart Chain",
      "miniName": "BNB",
      "unit":"BNB",
      "chainId": 56,
      "decimals": 18,
      "balance":'0',
      "balance_test":'0',
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BNB",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://bsc-dataseed1.binance.org/",
      "service_test": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "chainId_test": 97,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "BEP20",
    },
    "mainnetWS":"https://bsc-dataseed1.binance.org",
    "mainnetRPC":"https://bsc-dataseed1.binance.org",
    "mainnetChainID":0,
    "testnetWS":"https://data-seed-prebsc-1-s1.binance.org:8545",
    "testnetRPC":"https://data-seed-prebsc-1-s1.binance.org:8545",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://data-seed-prebsc-1-s1.binance.org:8545",
        "testnetRPC":"https://data-seed-prebsc-1-s1.binance.org:8545",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 6. ARB - Arbitrum（热门L2）
  CoinType.ARB.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ARB.name,
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum One",
      "miniName": "ARB",
      "unit":"ETH",
      "chainId": 42161,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ARB",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://arb1.arbitrum.io/rpc",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":42161,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 7. OP - Optimism（热门L2）
  CoinType.OP.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.OP.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Optimism Ethereum.png",
      "name": "Optimism",
      "miniName": "OP",
      "unit":"ETH",
      "chainId": 10,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "OP",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.optimism.io",
      "service_test": "https://kovan.optimism.io/",
      "chainId_test": 69,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":10,
    "testnetChainID":69,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://kovan.optimism.io/",
        "testnetChainID":69,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 8. BASE - Base（Coinbase L2，热门）
  CoinType.BASE.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "mKey": "BASE",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BASE.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/base.png",
      "name": "Base",
      "miniName": "BASE",
      "unit":"ETH",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.base.org",
      "service_test": "https://mainnet.base.org",
      "chainId": 8453,
      "chainId_test": 8453,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":8453,
    "testnetChainID":8453,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://mainnet.base.org",
        "testnetRPC":"https://mainnet.base.org",
        "testnetChainID":8453,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
      "0X833589FCD6EDB6E08F4C7C32D4F71B54BDA02913": <String,dynamic>{
        "mKey": "0X833589FCD6EDB6E08F4C7C32D4F71B54BDA02913",
        "blockchainType": BlockchainType.Ethereum.name,
        "coinType": CoinType.BASE.name,
        "icon": "https://api.n42.ai/market/v1/r/coinImage/USDC.png",
        "name": "USD Coin",
        "miniName": "USDC",
        "unit":"USDC",
        "decimals": 6,
        "balance":"0",
        "balance_test":"0",
        "coinPrice":0.0,
        "percentage":0.0,
        "isContract": true,
        "path": {
          "legacy":"m/44'/60'/0'/0/0",
        },
        "service": "https://mainnet.base.org",
        "service_test": "https://mainnet.base.org",
        "chainId": 8453,
        "chainId_test": 8453,
        "contract": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
        "contract_test": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
        "canEdit": true,
        "rules": "ERC20",
      },
    },
  },

  // 9. AVAX - Avalanche（热门公链）
  CoinType.AVAX.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.AVAX.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Avalanche C-Chain.png",
      "name": "Avalanche C-Chain",
      "miniName": "AVAX",
      "unit":"AVAX",
      "chainId": 43114,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "AVAX",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://api.avax.network/ext/bc/C/rpc",
      "service_test": "https://api.avax-test.network/ext/bc/C/rpc",
      "chainId_test": 43113,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":43114,
    "testnetChainID":43113,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://api.avax-test.network/ext/bc/C/rpc",
        "testnetChainID":43113,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 10. MATIC - Polygon（热门L2/侧链）
  CoinType.MATIC.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.MATIC.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Polygon.png",
      "name": "Polygon",
      "miniName": "MATIC",
      "unit":"MATIC",
      "chainId": 137,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "MATIC",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://polygon-rpc.com/",
      "service_test": "https://matic-mumbai.chainstacklabs.com",
      "chainId_test": 80001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":137,
    "testnetChainID":80001,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://matic-mumbai.chainstacklabs.com",
        "testnetChainID":80001,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 11. TON - The Open Network（热门，Telegram生态）
  CoinType.TON.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.TheOpenNetwork.name,
      "coinType": CoinType.TON.name,
      "icon": "https://cryptologos.cc/logos/toncoin-ton-logo.png",
      "name": "TON",
      "miniName": "TON",
      "unit":"TON",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "TON",
      "path": {
        "legacy":"m/44'/607'/0'",
      },
      "service": "https://toncenter.com/api/v2/jsonRPC",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "Jetton",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 12. TRX - Tron（活跃用户多，USDT主要流通链）
  CoinType.TRX.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Tron.name,
      "coinType": CoinType.TRX.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/TRON.png",
      "name": "Tron",
      "miniName": "TRX",
      "unit":"TRX",
      "chainId": 0,
      "decimals": 6,
      "balance":'0',
      "balance_test":'0',
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "TRX",
      "path": {
        "legacy":"m/44'/195'/0'/0/0",
      },
      "service": "https://api.trongrid.io/jsonrpc",
      "service_test": "https://nile.trongrid.io/jsonrpc",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "TRC20",
    },
    "mainnetWS":"https://api.trongrid.io",
    "mainnetRPC":"https://api.trongrid.io",
    "mainnetChainID":0,
    "testnetWS":"https://api.shasta.trongrid.io",
    "testnetRPC":"https://api.shasta.trongrid.io",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://api.shasta.trongrid.io",
        "testnetRPC":"https://api.shasta.trongrid.io",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 13. XRP - Ripple（知名度高）
  CoinType.XRP.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ripple.name,
      "coinType": CoinType.XRP.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/XRP.png",
      "name": "Ripple",
      "miniName": "XRP",
      "unit":"XRP",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "XRP",
      "path": {
        "legacy":"m/44'/144'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XRP",
    },
    "mainnetWS":"https://rpc.tulip.tools/mainnet",
    "mainnetRPC":"https://rpc.tulip.tools/mainnet",
    "mainnetChainID":0,
    "testnetWS":"https://rpc.tulip.tools/mainnet",
    "testnetRPC":"https://rpc.tulip.tools/mainnet",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://rpc.tulip.tools/mainnet",
        "testnetRPC":"https://rpc.tulip.tools/mainnet",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 14. ATOM - Cosmos（跨链生态核心）
  CoinType.ATOM.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Cosmos.name,
      "coinType": CoinType.ATOM.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Cosmos Hub.png",
      "name": "Cosmos",
      "miniName": "ATOM",
      "unit":"ATOM",
      "chainId": "cosmoshub-4",
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ATOM",
      "path": {
        "legacy":"m/44'/118'/0'/0/0",
      },
      "service": "https://cosmos-lcd.quickapi.com/",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ATOM",
    },
    "mainnetWS":"https://stargate.cosmos.network",
    "mainnetRPC":"https://stargate.cosmos.network",
    "mainnetChainID":0,
    "testnetWS":"https://stargate.cosmos.network",
    "testnetRPC":"https://stargate.cosmos.network",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://stargate.cosmos.network",
        "testnetRPC":"https://stargate.cosmos.network",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 15. DOT - Polkadot（知名跨链公链）
  CoinType.DOT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Polkadot.name,
      "coinType": CoinType.DOT.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Polkadot.png",
      "name": "Polkadot",
      "miniName": "DOT",
      "unit":"DOT",
      "chainId": 354,
      "decimals": 10,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "DOT",
      "path": {
        "legacy":"m/44'/354'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "DOT",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 16. FIL - Filecoin（存储公链）
  CoinType.FIL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Filecoin.name,
      "coinType": CoinType.FIL.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Filecoin.png",
      "name": "Filecoin",
      "miniName": "FIL",
      "unit":"FIL",
      "chainId": 461,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "FIL",
      "path": {
        "legacy":"m/44'/461'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "FIL",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 17. SUI - Sui（Move语言公链，热门）
  CoinType.SUI.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Sui.name,
      "coinType": CoinType.SUI.name,
      "icon": "https://cryptologos.cc/logos/sui-sui-logo.png",
      "name": "Sui",
      "miniName": "SUI",
      "unit":"SUI",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SUI",
      "path": {
        "legacy":"m/44'/784'/0'/0'/0'",
      },
      "service": "https://fullnode.mainnet.sui.io",
      "service_test": "https://fullnode.testnet.sui.io",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "SUI",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://fullnode.testnet.sui.io","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 18. APT - Aptos（Move语言公链）
  CoinType.APT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Aptos.name,
      "coinType": CoinType.APT.name,
      "icon": "https://cryptologos.cc/logos/aptos-apt-logo.png",
      "name": "Aptos",
      "miniName": "APT",
      "unit":"APT",
      "chainId": 1,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "APT",
      "path": {
        "legacy":"m/44'/637'/0'/0'/0'",
      },
      "service": "https://fullnode.mainnet.aptoslabs.com",
      "service_test": "https://fullnode.testnet.aptoslabs.com",
      "chainId_test": 2,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "APT",
    },
    "mainnetChainID":1,
    "testnetChainID":2,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://fullnode.testnet.aptoslabs.com","testnetChainID":2,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 19. ALGO - Algorand
};
