//walletList中使用 - Part 4: MON, WLD, IMX, TAIKO, ZKPOLYGON, DYDX, NTRN, KAVA, ONE, UNICHAIN, OPBNB, IOTX, FLR, DASH, KSM
import 'package:n42_wallet/features/component/enums/coin_type.dart';

Map<String,dynamic> walletChainConfigsPart4={
  // 51. MON - Monad
  CoinType.MON.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MON",
      "icon": "https://cryptologos.cc/logos/monad-mon-logo.png",
      "name": "Monad",
      "miniName": "MON",
      "unit": "MON",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.monad.xyz",
      "service_test": "",
      "chainId": 41454,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 41454,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 52. WLD - World Chain
  CoinType.WLD.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WLD",
      "icon": "https://cryptologos.cc/logos/worldcoin-wld-logo.png",
      "name": "World Chain",
      "miniName": "WLD",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WLD",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://worldchain-mainnet.g.alchemy.com/public",
      "service_test": "",
      "chainId": 480,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 480,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 53. IMX - Immutable zkEVM
  CoinType.IMX.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IMX",
      "icon": "https://cryptologos.cc/logos/immutable-imx-logo.png",
      "name": "Immutable zkEVM",
      "miniName": "IMX",
      "unit": "IMX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IMX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.immutable.com",
      "service_test": "",
      "chainId": 13371,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 13371,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 54. TAIKO - Taiko
  CoinType.TAIKO.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TAIKO",
      "icon": "https://cryptologos.cc/logos/taiko-taiko-logo.png",
      "name": "Taiko",
      "miniName": "TAIKO",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TAIKO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mainnet.taiko.xyz",
      "service_test": "",
      "chainId": 167000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 167000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 55. ZKPOLYGON - Polygon zkEVM
  CoinType.ZKPOLYGON.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKPOLYGON",
      "icon": "https://cryptologos.cc/logos/polygon-matic-logo.png",
      "name": "Polygon zkEVM",
      "miniName": "zkPOL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKPOLYGON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://zkevm-rpc.com",
      "service_test": "",
      "chainId": 1101,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1101,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 56. DYDX - dYdX
  CoinType.DYDX.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "DYDX",
      "icon": "https://cryptologos.cc/logos/dydx-dydx-logo.png",
      "name": "dYdX",
      "miniName": "DYDX",
      "unit": "DYDX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DYDX",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://dydx-rest.publicnode.com",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "dydx"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 57. NTRN - Neutron
  CoinType.NTRN.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "NTRN",
      "icon": "https://cryptologos.cc/logos/neutron-ntrn-logo.png",
      "name": "Neutron",
      "miniName": "NTRN",
      "unit": "NTRN",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NTRN",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://neutron-rest.publicnode.com",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "neutron"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 58. KAVA - Kava EVM
  CoinType.KAVA.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KAVA",
      "icon": "https://cryptologos.cc/logos/kava-kava-logo.png",
      "name": "Kava EVM",
      "miniName": "KAVA",
      "unit": "KAVA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KAVA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.kava.io",
      "service_test": "",
      "chainId": 2222,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2222,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 59. ONE - Harmony
  CoinType.ONE.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ONE",
      "icon": "https://www.n42.ai/static/one.png",
      "name": "Harmony",
      "miniName": "ONE",
      "unit": "one",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ONE",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://api.harmony.one",
      "service_test": "https://api.s0.b.hmny.io",
      "chainId": 1666600000,
      "chainId_test": 1666700000,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "HRC20"
    },
    "mainnetChainID": 1666600000,
    "testnetChainID": 1666700000,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://api.s0.b.hmny.io", "testnetChainID": 1666700000, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 60. UNICHAIN - Unichain
  CoinType.UNICHAIN.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "UNICHAIN",
      "icon": "https://cryptologos.cc/logos/uniswap-uni-logo.png",
      "name": "Unichain",
      "miniName": "UNI",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "UNICHAIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.unichain.org",
      "service_test": "",
      "chainId": 130,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 130,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 61. OPBNB - opBNB
  CoinType.OPBNB.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OPBNB",
      "icon": "https://cryptologos.cc/logos/bnb-bnb-logo.png",
      "name": "opBNB",
      "miniName": "opBNB",
      "unit": "BNB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OPBNB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://opbnb-mainnet-rpc.bnbchain.org",
      "service_test": "",
      "chainId": 204,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 204,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 62. IOTX - IoTeX
  CoinType.IOTX.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IOTX",
      "icon": "https://www.n42.ai/static/iotx.png",
      "name": "IoTeX",
      "miniName": "IOTX",
      "unit": "iotx",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IOTX",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://babel-api.mainnet.iotex.io",
      "service_test": "https://babel-api.testnet.iotex.io",
      "chainId": 4689,
      "chainId_test": 4690,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XRC20"
    },
    "mainnetChainID": 4689,
    "testnetChainID": 4690,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://babel-api.testnet.iotex.io", "testnetChainID": 4690, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 63. FLR - Flare
  CoinType.FLR.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FLR",
      "icon": "https://cryptologos.cc/logos/flare-flr-logo.png",
      "name": "Flare",
      "miniName": "FLR",
      "unit": "FLR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FLR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://flare-api.flare.network/ext/C/rpc",
      "service_test": "",
      "chainId": 14,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 14,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 64. DASH - Dash
  CoinType.DASH.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DASH",
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Dash.png",
      "name": "Dash",
      "miniName": "DASH",
      "unit": "dash",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DASH",
      "path": {
        "legacy": "m/44'/5'/0'/0/0"
      },
      "service": "",
      "service_test": "http://seed-1.testnet.networks.dash.org:3000/",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "http://seed-1.testnet.networks.dash.org:3000/", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },

  // 65. KSM - Kusama
  CoinType.KSM.name:<String,dynamic>{
    "showList":true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Polkadot",
      "coinType": "KSM",
      "icon": "https://cryptologos.cc/logos/kusama-ksm-logo.png",
      "name": "Kusama",
      "miniName": "KSM",
      "unit": "KSM",
      "decimals": 12,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KSM",
      "path": {"legacy": "m/44'/434'/0'/0'/0'"},
      "service": "https://kusama-rpc.polkadot.io",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
