//walletList中使用 - Part 3: ADA, VET, XLM, HBAR, EGLD, BCH, INJ, OSMO, TIA, S, HYPE, BERA, RON, STRK, SEI
import 'package:n42_wallet/features/component/enums/coin_type.dart';

Map<String, dynamic> walletChainConfigsPart3 = {
  // 36. ADA - Cardano
  CoinType.ADA.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Cardano",
      "coinType": "ADA",
      "icon": "https://www.n42.ai/static/ada.png",
      "name": "Cardano",
      "miniName": "ADA",
      "unit": "ada",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ADA",
      "path": {"legacy": "m/1852'/1815'/0'/0/0"},
      "service": "https://cardano-mainnet.blockfrost.io/api/v0",
      "service_test": "https://cardano-preprod.blockfrost.io/api/v0",
      "chainId": 1,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetChainID": 1,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "https://cardano-preprod.blockfrost.io/api/v0",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 37. VET - VeChain
  CoinType.VET.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "VeChain",
      "coinType": "VET",
      "icon": "https://www.n42.ai/static/vet.png",
      "name": "VeChain",
      "miniName": "VET",
      "unit": "vet",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "VET",
      "path": {"legacy": "m/44'/818'/0'/0/0"},
      "service": "https://mainnet.veblocks.net",
      "service_test": "https://testnet.veblocks.net",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "VIP180",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "https://testnet.veblocks.net",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 38. XLM - Stellar
  CoinType.XLM.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Stellar",
      "coinType": "XLM",
      "icon": "https://www.n42.ai/static/xlm.png",
      "name": "Stellar",
      "miniName": "XLM",
      "unit": "xlm",
      "decimals": 7,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XLM",
      "path": {"legacy": "m/44'/148'/0'"},
      "service": "https://horizon.stellar.org",
      "service_test": "https://horizon-testnet.stellar.org",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "https://horizon-testnet.stellar.org",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 39. HBAR - Hedera
  CoinType.HBAR.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HBAR",
      "icon": "https://cryptologos.cc/logos/hedera-hbar-logo.png",
      "name": "Hedera",
      "miniName": "HBAR",
      "unit": "HBAR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HBAR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.hashio.io/api",
      "service_test": "",
      "chainId": 295,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 295,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 40. EGLD - MultiversX
  CoinType.EGLD.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "MultiversX",
      "coinType": "EGLD",
      "icon": "https://www.n42.ai/static/egld.png",
      "name": "MultiversX",
      "miniName": "EGLD",
      "unit": "egld",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EGLD",
      "path": {"legacy": "m/44'/508'/0'/0/0"},
      "service": "https://gateway.multiversx.com",
      "service_test": "https://devnet-gateway.multiversx.com",
      "chainId": 1,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ESDT",
    },
    "mainnetChainID": 1,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "https://devnet-gateway.multiversx.com",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 41. BCH - Bitcoin Cash
  CoinType.BCH.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "BCH",
      "icon": "https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png",
      "name": "Bitcoin Cash",
      "miniName": "BCH",
      "unit": "bch",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BCH",
      "path": {"legacy": "m/44'/145'/0'/0/0"},
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 42. INJ - Injective
  CoinType.INJ.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "INJ",
      "icon": "https://cryptologos.cc/logos/injective-inj-logo.png",
      "name": "Injective",
      "miniName": "INJ",
      "unit": "INJ",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "INJ",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rest.cosmos.directory/injective",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "inj",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 43. OSMO - Osmosis
  CoinType.OSMO.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "OSMO",
      "icon": "https://cryptologos.cc/logos/osmosis-osmo-logo.png",
      "name": "Osmosis",
      "miniName": "OSMO",
      "unit": "OSMO",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OSMO",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://osmosis-rest.publicnode.com",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "osmo",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 44. TIA - Celestia
  CoinType.TIA.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "TIA",
      "icon": "https://cryptologos.cc/logos/celestia-tia-logo.png",
      "name": "Celestia",
      "miniName": "TIA",
      "unit": "TIA",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TIA",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://celestia-rest.publicnode.com",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "celestia",
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 45. S - Sonic
  CoinType.S.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "S",
      "icon": "https://cryptologos.cc/logos/sonic-s-logo.png",
      "name": "Sonic",
      "miniName": "S",
      "unit": "S",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "S",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.soniclabs.com",
      "service_test": "",
      "chainId": 146,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 146,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 46. HYPE - Hyperliquid
  CoinType.HYPE.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HYPE",
      "icon": "https://cryptologos.cc/logos/hyperliquid-hype-logo.png",
      "name": "Hyperliquid",
      "miniName": "HYPE",
      "unit": "HYPE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HYPE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.hyperliquid.xyz/evm",
      "service_test": "",
      "chainId": 998,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 998,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 47. BERA - Berachain
  CoinType.BERA.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BERA",
      "icon": "https://cryptologos.cc/logos/berachain-bera-logo.png",
      "name": "Berachain",
      "miniName": "BERA",
      "unit": "BERA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BERA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.berachain.com",
      "service_test": "",
      "chainId": 80094,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 80094,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 48. RON - Ronin
  CoinType.RON.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "RON",
      "icon": "https://cryptologos.cc/logos/ronin-ron-logo.png",
      "name": "Ronin",
      "miniName": "RON",
      "unit": "RON",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.roninchain.com",
      "service_test": "",
      "chainId": 2020,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 2020,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 49. STRK - Starknet
  CoinType.STRK.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Starknet",
      "coinType": "STRK",
      "icon": "https://cryptologos.cc/logos/starknet-strk-logo.png",
      "name": "Starknet",
      "miniName": "STRK",
      "unit": "STRK",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "STRK",
      "path": {"legacy": "m/44'/9004'/0'/0/0"},
      "service": "https://starknet-mainnet.public.blastapi.io",
      "service_test": "https://starknet-sepolia.public.blastapi.io",
      "chainId": "23448594291968334",
      "chainId_test": "1536727068981429685",
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
      "starknetChainId": "SN_MAIN",
      "starknetChainId_test": "SN_SEPOLIA",
    },
    "mainnetChainID": "23448594291968334",
    "testnetChainID": "1536727068981429685",
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "https://starknet-sepolia.public.blastapi.io",
        "testnetChainID": "1536727068981429685",
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },

  // 50. SEI - Sei
  CoinType.SEI.name: <String, dynamic>{
    "showList": true,
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String, dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SEI",
      "icon": "https://cryptologos.cc/logos/sei-sei-logo.png",
      "name": "Sei",
      "miniName": "SEI",
      "unit": "SEI",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SEI",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm-rpc.sei-apis.com",
      "service_test": "",
      "chainId": 1329,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID": 1329,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [
      {
        "testnetWS": "",
        "testnetRPC": "",
        "testnetChainID": 0,
        "testnetContract": <String, dynamic>{},
      },
    ],
    "mainnets": <String, dynamic>{},
    "mainnetContract": {},
    "testnetContract": {},
  },
};
