{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-rc-1",
      "buildId:": "16115938"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.6.2-sources.jar",
          "url": "camera-core-1.6.2-sources.jar",
          "size": 808290,
          "sha512": "201f190a437e12f69e25dc17fbb5463f78d39ae3e94f6c748d815e2b55aad49cf5325d5a86ccf1074b6265d7e539595c533c50330e5ac3e71a8fec249caf2904",
          "sha256": "9803a0c47248a567c99dbc1b95e07afb8ccc5a7e097ce3f76dd126be3a53ee44",
          "sha1": "9bbc19898cc00fb6d05b44cbdaf956f9e28a5ee1",
          "md5": "7fb1bda79b82125c06f4bbc82a41d1b2"
        },
        {
          "name": "camera-core-1.6.2-samples-sources.jar",
          "url": "camera-core-1.6.2-samples-sources.jar",
          "size": 7830,
          "sha512": "b930ad4e1071b44c7fec30c8aa5302c27a276776c4a8d2354d7fa73acd9a26177e823bc2e5ad257d3920c78bfe284d4ca5fb01787a2abdbe19a5bdf494dfda63",
          "sha256": "d70c01d96bbe4abbb691312514f6708f9ba866f38003d698db31eda2a529a9c9",
          "sha1": "e5ad3a6829c7028afec1734ce24b9b7ed33951bc",
          "md5": "472f33742422c59a2853c4cc96fa331a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.6.2.aar",
          "url": "camera-core-1.6.2.aar",
          "size": 1213194,
          "sha512": "78e997c7d29b68794bfd41997c37f57a2d1637173635fc92658ab1fb9243354b783c75de26d146c4f0f3b72be23fe732c94b3ca1be1b34912c39575b6e91ff18",
          "sha256": "ebd66f090414f4c12f23a55b5023aeee1b096da8a06c02a0b6fb3520c4ddadf6",
          "sha1": "73a5452def0669481fe649874b94e326ebbfd6ff",
          "md5": "997477e51e99138641b07f4a604e47b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-backported-fixes",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.6.2.aar",
          "url": "camera-core-1.6.2.aar",
          "size": 1213194,
          "sha512": "78e997c7d29b68794bfd41997c37f57a2d1637173635fc92658ab1fb9243354b783c75de26d146c4f0f3b72be23fe732c94b3ca1be1b34912c39575b6e91ff18",
          "sha256": "ebd66f090414f4c12f23a55b5023aeee1b096da8a06c02a0b6fb3520c4ddadf6",
          "sha1": "73a5452def0669481fe649874b94e326ebbfd6ff",
          "md5": "997477e51e99138641b07f4a604e47b8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.6.2-versionMetadata.json",
          "url": "camera-core-1.6.2-versionMetadata.json",
          "size": 46477,
          "sha512": "d63906588c827aa9c0dc0da42db349141fedd385183c9ba19e0f1ad36bda5aa2fa8d78d0cebfce7a82725e2794eacd3bbc771d8f1649d04fdb193aaacd40ef86",
          "sha256": "83f78b93f72ae88a3bb17ad4c2abcc99a85625262fe2f468b3658bc783af808d",
          "sha1": "4c0523cf9c581e72d5907918c2432c76cf2c5cc6",
          "md5": "4c513f2e9285897a67e0402285510b7e"
        }
      ]
    }
  ]
}