import 'package:n42appv2/src/component/enums/coin_type.dart';

Map<String,dynamic> allChainUrlMap=<String,dynamic>{
  CoinType.N.name:<String,dynamic>{
    "showList":true,//主链币是否显示在主页列表中
    "isTest":false,//是否时正式链
    "supportTest":true,
    "addrType":"legacy",//地址类型
    "pathIndex":0,//path具体的账号节点
    "pathList":[0],//path数量
    "baseInfo":<String,dynamic>{
      "mKey": "N",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.N.name,
      "icon": "https://n42.ai/static/n42.png",
      "name": "N42",
      "miniName": "N",
      "unit":"N",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "http://18.170.108.78:20012",
      "service_test": "http://54.243.83.152:20012",
      "chainId": 94,//100100100,
      "chainId_test": 1142,//100100100,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    //"mainnetWS":"ws://174.129.114.74:8546",
    //"mainnetRPC":"http://174.129.114.74:8545",//"http://192.168.0.190:20012",//
    "mainnetChainID":94,//100100100,
    //"testnetWS":"ws://174.129.114.74:8546",
    //"testnetRPC":"http://174.129.114.74:8545",//"http://192.168.0.190:20012",//
    "testnetChainID":1142,
    "testnetIndex":0,//当前选择的测试网络 索引值
    "testnets":[
      {
        "testnetWS":"ws://54.175.247.94:20012",
        "testnetRPC":"http://54.243.83.152:20012",
        "testnetChainID":1142,//100100100,//
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
      "erc1155":"0x7632cA0FE8CBE97a59c600e5Afb3e75B9eC3Dc05",
      "erc721":"0xD535A5DAC95E5D5C9E121E20257E71a8FED74d95",
      "Market":"0x60a073d2F24884212859B10161590d7A67e225F9",
      "NftAddress":"0x70c8A83193a23Dd49Db33996570A573960Cf7653",//nft转账收款地址
    },
    "testnetContract":{
      "erc1155":"0xfd89417A8BE37e27162376b3a76E1EA2e1d930A9",
      "erc721":"0x1b035d6a285682De59f3b529e53D7D14b652014f",
      "Market":"0x958Bb3Fd435aC84302E8f3dE582730860825f00a",
      "NftAddress":"0xd02Da544Aa8F09F16c0FE28CA0C53772C95FB146",//nft转账收款地址
      /*"erc1155":"0x38523DAc202B9bdCe0c642E0B165F2dafe2d328c",
      "erc721":"0x1EA69cf17D3d249E545190a22213F98E47cb1379",
      "Market":"0xbA020608A5A03602d0C7D0BA64B430f1fBF65E34",*/
    },
    //挖矿合约地址
    "miningContract": "0x581231E78f9C15882ace8b6597b619999aeD5137"
  },
  CoinType.AVAX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "AVAX",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Avalanche C-Chain.png",
      "name": "Avalanche C-Chain",
      "miniName": "AVAX",
      "unit": "avax",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "AVAX",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://api.avax.network/ext/bc/C/rpc",
      "service_test": "https://api.avax-test.network/ext/bc/C/rpc",
      "chainId": 43114,
      "chainId_test": 43113,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 43114,
    "testnetChainID": 43113,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.avax-test.network/ext/bc/C/rpc",
      "testnetChainID": 43113,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BASE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BASE",
      "icon": "https://www.n42.ai/static/base.png",
      "name": "Base",
      "miniName": "BASE",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BASE",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://endpoints.omniatech.io/v1/base/mainnet/public",
      "service_test": "",
      "chainId": 8453,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 8453,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BNB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BNB",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Binance Smart Chain.png",
      "name": "Binance Smart Chain",
      "miniName": "BNB",
      "unit": "bnb",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BNB",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://bsc-dataseed1.binance.org/",
      "service_test": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "chainId": 56,
      "chainId_test": 97,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "BEP20"
    },
    "mainnetChainID": 56,
    "testnetChainID": 97,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "testnetChainID": 97,
      "testnetContract":<String,dynamic> {}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "BTC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Bitcoin.png",
      "name": "Bitcoin",
      "miniName": "BTC",
      "unit": "btc",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BTC",
      "path": {
        "segwit": "m/84'/0'/0'/0/0",
        "legacy": "m/44'/0'/0'/0/0",
        "taproot":"m/86'/0'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BOBA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BOBA",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Boba Network.png",
      "name": "Boba Network",
      "miniName": "BOBA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BOBA",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.boba.network",
      "service_test": "https://rinkeby.boba.network/",
      "chainId": 288,
      "chainId_test": 28,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 288,
    "testnetChainID": 28,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rinkeby.boba.network/",
      "testnetChainID": 28,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CELO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CELO",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Celo.png",
      "name": "Celo",
      "miniName": "CELO",
      "unit": "celo",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CELO",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://forno.celo.org/",
      "service_test": "https://alfajores-forno.celo-testnet.org",
      "chainId": 42220,
      "chainId_test": 44787,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42220,
    "testnetChainID": 44787,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://alfajores-forno.celo-testnet.org",
      "testnetChainID": 44787,
      "testnetContract": {}
    }],
    "mainnets": {},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DASH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DASH",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Dash.png",
      "name": "Dash",
      "miniName": "DASH",
      "unit": "dash",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DASH",
      "path": {
        "legacy": "m/44'/5'/0'/0/0"
      },
      "service": "",
      "service_test": "http://seed-1.testnet.networks.dash.org:3000/",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "http://seed-1.testnet.networks.dash.org:3000/",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DOGE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DOGE",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Dogecoin.png",
      "name": "Dogecoin",
      "miniName": "DOGE",
      "unit": "doge",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DOGE",
      "path": {
        "legacy": "m/44'/3'/0'/0/0"
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ETH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ETH",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Ethereum.png",
      "name": "Ethereum",
      "miniName": "ETH",
      "unit": "eth",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ETH",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "service_test": "https://ropsten.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "chainId": 1,
      "chainId_test": 3,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1,
    "testnetChainID": 3,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://ropsten.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "testnetChainID": 3,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ETC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ETC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Ethereum Classic.png",
      "name": "Ethereum Classic",
      "miniName": "ETC",
      "unit": "etc",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ETC",
      "path": {
        "legacy": "m/44'/61'/0'/0/0"
      },
      "service": "https://etc.rivet.link",
      "service_test": "https://rpc.mordor.etccooperative.org/",
      "chainId": 61,
      "chainId_test": 6,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 61,
    "testnetChainID": 6,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc.mordor.etccooperative.org/",
      "testnetChainID": 6,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FTM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FTM",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Fantom.png",
      "name": "Fantom",
      "miniName": "FTM",
      "unit": "ftm",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FTM",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.ankr.com/fantom/",
      "service_test": "https://rpc.testnet.fantom.network",
      "chainId": 250,
      "chainId_test": 4002,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 250,
    "testnetChainID": 4002,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc.testnet.fantom.network",
      "testnetChainID": 4002,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GO",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/GoChain.png",
      "name": "GoChain",
      "miniName": "GO",
      "unit": "go",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GO",
      "path": {
        "legacy": "m/44'/6060'/0'/0/0"
      },
      "service": "https://rpc.gochain.io",
      "service_test": "https://testnet-rpc.gochain.io",
      "chainId": 60,
      "chainId_test": 31337,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 60,
    "testnetChainID": 31337,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://testnet-rpc.gochain.io",
      "testnetChainID": 31337,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Huobi ECO Chain.png",
      "name": "Huobi ECO Chain",
      "miniName": "HT",
      "unit": "ht",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HT",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://http-mainnet.hecochain.com",
      "service_test": "https://http-testnet.hecochain.com",
      "chainId": 128,
      "chainId_test": 256,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 128,
    "testnetChainID": 256,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://http-testnet.hecochain.com",
      "testnetChainID": 256,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KLAY.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KLAY",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Klaytn.png",
      "name": "Klaytn",
      "miniName": "KLAY",
      "unit": "klay",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KLAY",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://klaytn.blockpi.network/v1/rpc/public",
      "service_test": "https://api.baobab.klaytn.net:8651",
      "chainId": 8217,
      "chainId_test": 1001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 8217,
    "testnetChainID": 1001,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.baobab.klaytn.net:8651",
      "testnetChainID": 1001,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KCS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KCS",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/KuCoin Community Chain.png",
      "name": "KuCoin Community Chain",
      "miniName": "KCS",
      "unit": "kcs",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KCS",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc-mainnet.kcc.network",
      "service_test": "https://rpc-testnet.kcc.network",
      "chainId": 321,
      "chainId_test": 322,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 321,
    "testnetChainID": 322,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc-testnet.kcc.network",
      "testnetChainID": 322,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "LTC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Litecoin.png",
      "name": "Litecoin",
      "miniName": "LTC",
      "unit": "ltc",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LTC",
      "path": {
        "segwit": "m/84'/2'/0'/0/0",
        "legacy": "m/44'/2'/0'/0/0"
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MTR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MTR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Meter.png",
      "name": "Meter",
      "miniName": "MTR",
      "unit": "mtr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MTR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.meter.io",
      "service_test": "https://rpctest.meter.io",
      "chainId": 82,
      "chainId_test": 83,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 82,
    "testnetChainID": 83,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpctest.meter.io",
      "testnetChainID": 83,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.METIS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "METIS",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Metis.png",
      "name": "Metis",
      "miniName": "METIS",
      "unit": "metis",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "METIS",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://andromeda.metis.io/?owner=1088",
      "service_test": "https://stardust.metis.io/?owner=588",
      "chainId": 1088,
      "chainId_test": 588,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1088,
    "testnetChainID": 588,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://stardust.metis.io/?owner=588",
      "testnetChainID": 588,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GLMR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GLMR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Moonbeam.png",
      "name": "Moonbeam",
      "miniName": "GLMR",
      "unit": "glmr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GLMR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.api.moonbeam.network",
      "service_test": "https://moonbase-alpha.public.blastapi.io/",
      "chainId": 1284,
      "chainId_test": 1287,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1284,
    "testnetChainID": 1287,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://moonbase-alpha.public.blastapi.io/",
      "testnetChainID": 1287,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MOVR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MOVR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Moonriver.png",
      "name": "Moonriver",
      "miniName": "MOVR",
      "unit": "movr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MOVR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://moonriver.public.blastapi.io",
      "service_test": "",
      "chainId": 1285,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1285,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OKT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OKT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/OKX Chain.png",
      "name": "OKX Chain",
      "miniName": "OKT",
      "unit": "okt",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OKT",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://exchainrpc.okex.org",
      "service_test": "https://exchaintestrpc.okex.org",
      "chainId": 66,
      "chainId_test": 65,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 66,
    "testnetChainID": 65,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://exchaintestrpc.okex.org",
      "testnetChainID": 65,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OP.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OP",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Optimism Ethereum.png",
      "name": "Optimism Ethereum",
      "miniName": "OP",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OP",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.optimism.io",
      "service_test": "https://kovan.optimism.io/",
      "chainId": 10,
      "chainId_test": 69,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 10,
    "testnetChainID": 69,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://kovan.optimism.io/",
      "testnetChainID": 69,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MATIC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MATIC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Polygon.png",
      "name": "Polygon",
      "miniName": "MATIC",
      "unit": "matic",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MATIC",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://polygon-rpc.com/",
      "service_test": "https://matic-mumbai.chainstacklabs.com",
      "chainId": 137,
      "chainId_test": 80001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 137,
    "testnetChainID": 80001,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://matic-mumbai.chainstacklabs.com",
      "testnetChainID": 80001,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SOL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Solana",
      "coinType": "SOL",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Solana.png",
      "name": "Solana",
      "miniName": "SOL",
      "unit": "sol",
      "decimals": 9,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SOL",
      "path": {
        "legacy": "m/44'/501'/0'"
      },
      "service": "https://api.mainnet-beta.solana.com",
      "service_test": "http://api.testnet.solana.com",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "SPL"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "http://api.testnet.solana.com",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Thunder Token.png",
      "name": "Thunder Token",
      "miniName": "TT",
      "unit": "tt",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TT",
      "path": {
        "legacy": "m/44'/1001'/0'/0/0"
      },
      "service": "https://mainnet-rpc.thundercore.com",
      "service_test": "https://testnet-rpc.thundercore.com",
      "chainId": 108,
      "chainId_test": 18,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 108,
    "testnetChainID": 18,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://testnet-rpc.thundercore.com",
      "testnetChainID": 18,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TRX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Tron",
      "coinType": "TRX",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Tron.png",
      "name": "Tron",
      "miniName": "TRX",
      "unit": "trx",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TRX",
      "path": {
        "legacy": "m/44'/195'/0'/0/0"
      },
      "service": "https://api.trongrid.io",
      "service_test": "https://api.shasta.trongrid.io",
      "chainId": 728126428,
      "chainId_test": 2494104990,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "TRC20"
    },
    "mainnetChainID": 728126428,
    "testnetChainID": 2494104990,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.shasta.trongrid.io",
      "testnetChainID": 2494104990,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WAN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WAN",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/wanChain.png",
      "name": "wanChain",
      "miniName": "WAN",
      "unit": "wan",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WAN",
      "path": {
        "legacy": "m/44'/5718350'/0'/0/0"
      },
      "service": "https://gwan-ssl.wandevs.org:56891",
      "service_test": "https://gwan-ssl.wandevs.org:46891/",
      "chainId": 888,
      "chainId_test": 999,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 888,
    "testnetChainID": 999,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://gwan-ssl.wandevs.org:46891/",
      "testnetChainID": 999,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XLM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Stellar",
      "coinType": "XLM",
      "icon": "https://www.n42.ai/static/xlm.png",
      "name": "Stellar",
      "miniName": "XLM",
      "unit": "xlm",
      "decimals": 7,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XLM",
      "path": {
        "legacy": "m/44'/148'/0'"
      },
      "service": "https://horizon.stellar.org",
      "service_test": "https://horizon-testnet.stellar.org",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://horizon-testnet.stellar.org",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.VET.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "VeChain",
      "coinType": "VET",
      "icon": "https://www.n42.ai/static/vet.png",
      "name": "VeChain",
      "miniName": "VET",
      "unit": "vet",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "VET",
      "path": {
        "legacy": "m/44'/818'/0'/0/0"
      },
      "service": "https://mainnet.veblocks.net",
      "service_test": "https://testnet.veblocks.net",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "VIP180"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://testnet.veblocks.net",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ONE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ONE",
      "icon": "https://www.n42.ai/static/one.png",
      "name": "Harmony",
      "miniName": "ONE",
      "unit": "one",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ONE",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://api.harmony.one",
      "service_test": "https://api.s0.b.hmny.io",
      "chainId": 1666600000,
      "chainId_test": 1666700000,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "HRC20"
    },
    "mainnetChainID": 1666600000,
    "testnetChainID": 1666700000,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.s0.b.hmny.io",
      "testnetChainID": 1666700000,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.IOTX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IOTX",
      "icon": "https://www.n42.ai/static/iotx.png",
      "name": "IoTeX",
      "miniName": "IOTX",
      "unit": "iotx",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IOTX",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://babel-api.mainnet.iotex.io",
      "service_test": "https://babel-api.testnet.iotex.io",
      "chainId": 4689,
      "chainId_test": 4690,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XRC20"
    },
    "mainnetChainID": 4689,
    "testnetChainID": 4690,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://babel-api.testnet.iotex.io",
      "testnetChainID": 4690,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NEAR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Near",
      "coinType": "NEAR",
      "icon": "https://www.n42.ai/static/near.png",
      "name": "NEAR Protocol",
      "miniName": "NEAR",
      "unit": "near",
      "decimals": 24,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NEAR",
      "path": {
        "legacy": "m/44'/397'/0'"
      },
      "service": "https://rpc.mainnet.near.org",
      "service_test": "https://rpc.testnet.near.org",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "NEP141"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc.testnet.near.org",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZIL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Zilliqa",
      "coinType": "ZIL",
      "icon": "https://www.n42.ai/static/zil.png",
      "name": "Zilliqa",
      "miniName": "ZIL",
      "unit": "zil",
      "decimals": 12,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZIL",
      "path": {
        "legacy": "m/44'/313'/0'/0/0"
      },
      "service": "https://api.zilliqa.com",
      "service_test": "https://dev-api.zilliqa.com",
      "chainId": 1,
      "chainId_test": 333,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ZRC2"
    },
    "mainnetChainID": 1,
    "testnetChainID": 333,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://dev-api.zilliqa.com",
      "testnetChainID": 333,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.THETA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Theta",
      "coinType": "THETA",
      "icon": "https://www.n42.ai/static/theta.png",
      "name": "Theta Network",
      "miniName": "THETA",
      "unit": "theta",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "THETA",
      "path": {
        "legacy": "m/44'/500'/0'/0/0"
      },
      "service": "https://eth-rpc-api.thetatoken.org/rpc",
      "service_test": "https://eth-rpc-api-testnet.thetatoken.org/rpc",
      "chainId": 361,
      "chainId_test": 365,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "TNT20"
    },
    "mainnetChainID": 361,
    "testnetChainID": 365,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://eth-rpc-api-testnet.thetatoken.org/rpc",
      "testnetChainID": 365,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ADA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cardano",
      "coinType": "ADA",
      "icon": "https://www.n42.ai/static/ada.png",
      "name": "Cardano",
      "miniName": "ADA",
      "unit": "ada",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ADA",
      "path": {
        "legacy": "m/1852'/1815'/0'/0/0"
      },
      "service": "https://cardano-mainnet.blockfrost.io/api/v0",
      "service_test": "https://cardano-preprod.blockfrost.io/api/v0",
      "chainId": 1,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": ""
    },
    "mainnetChainID": 1,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://cardano-preprod.blockfrost.io/api/v0",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.EGLD.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "MultiversX",
      "coinType": "EGLD",
      "icon": "https://www.n42.ai/static/egld.png",
      "name": "MultiversX",
      "miniName": "EGLD",
      "unit": "egld",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EGLD",
      "path": {
        "legacy": "m/44'/508'/0'/0/0"
      },
      "service": "https://gateway.multiversx.com",
      "service_test": "https://devnet-gateway.multiversx.com",
      "chainId": 1,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ESDT"
    },
    "mainnetChainID": 1,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://devnet-gateway.multiversx.com",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 1: Mainstream L2 Chains ============
  CoinType.ARB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ARB",
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum One",
      "miniName": "ARB",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ARB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://arb1.arbitrum.io/rpc",
      "service_test": "",
      "chainId": 42161,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42161,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZKSYNC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKSYNC",
      "icon": "https://cryptologos.cc/logos/zksync-zk-logo.png",
      "name": "zkSync Era",
      "miniName": "ZK",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKSYNC",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.era.zksync.io",
      "service_test": "",
      "chainId": 324,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 324,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LINEA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "LINEA",
      "icon": "https://cryptologos.cc/logos/linea-linea-logo.png",
      "name": "Linea",
      "miniName": "LINEA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LINEA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.linea.build",
      "service_test": "",
      "chainId": 59144,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 59144,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SCROLL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SCROLL",
      "icon": "https://cryptologos.cc/logos/scroll-scr-logo.png",
      "name": "Scroll",
      "miniName": "SCROLL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SCROLL",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.scroll.io",
      "service_test": "",
      "chainId": 534352,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 534352,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MNT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MNT",
      "icon": "https://cryptologos.cc/logos/mantle-mnt-logo.png",
      "name": "Mantle",
      "miniName": "MNT",
      "unit": "MNT",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MNT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mantle.xyz",
      "service_test": "",
      "chainId": 5000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 5000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BLAST.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BLAST",
      "icon": "https://cryptologos.cc/logos/blast-blast-logo.png",
      "name": "Blast",
      "miniName": "BLAST",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BLAST",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.blast.io",
      "service_test": "",
      "chainId": 81457,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 81457,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NOVA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "NOVA",
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum Nova",
      "miniName": "NOVA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NOVA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://nova.arbitrum.io/rpc",
      "service_test": "",
      "chainId": 42170,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42170,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 2: Other Mainstream L1/L2 ============
  CoinType.CRO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CRO",
      "icon": "https://cryptologos.cc/logos/cronos-cro-logo.png",
      "name": "Cronos",
      "miniName": "CRO",
      "unit": "CRO",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CRO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.cronos.org",
      "service_test": "",
      "chainId": 25,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 25,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GNOSIS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GNOSIS",
      "icon": "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png",
      "name": "Gnosis Chain",
      "miniName": "xDAI",
      "unit": "xDAI",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GNOSIS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gnosischain.com",
      "service_test": "",
      "chainId": 100,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 100,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.AURORA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "AURORA",
      "icon": "https://cryptologos.cc/logos/aurora-aurora-logo.png",
      "name": "Aurora",
      "miniName": "AURORA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "AURORA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.aurora.dev",
      "service_test": "",
      "chainId": 1313161554,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1313161554,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FUSE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FUSE",
      "icon": "https://cryptologos.cc/logos/fuse-fuse-logo.png",
      "name": "Fuse",
      "miniName": "FUSE",
      "unit": "FUSE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FUSE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.fuse.io",
      "service_test": "",
      "chainId": 122,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 122,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZKPOLYGON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZKPOLYGON",
      "icon": "https://cryptologos.cc/logos/polygon-matic-logo.png",
      "name": "Polygon zkEVM",
      "miniName": "zkPOL",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZKPOLYGON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://zkevm-rpc.com",
      "service_test": "",
      "chainId": 1101,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1101,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MODE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MODE",
      "icon": "https://cryptologos.cc/logos/mode-mode-logo.png",
      "name": "Mode",
      "miniName": "MODE",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MODE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.mode.network",
      "service_test": "",
      "chainId": 34443,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 34443,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MANTA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MANTA",
      "icon": "https://cryptologos.cc/logos/manta-network-manta-logo.png",
      "name": "Manta Pacific",
      "miniName": "MANTA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MANTA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://pacific-rpc.manta.network/http",
      "service_test": "",
      "chainId": 169,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 169,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CANTO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CANTO",
      "icon": "https://cryptologos.cc/logos/canto-canto-logo.png",
      "name": "Canto",
      "miniName": "CANTO",
      "unit": "CANTO",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CANTO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://canto.slingshot.finance",
      "service_test": "",
      "chainId": 7700,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7700,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KAVA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KAVA",
      "icon": "https://cryptologos.cc/logos/kava-kava-logo.png",
      "name": "Kava EVM",
      "miniName": "KAVA",
      "unit": "KAVA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KAVA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.kava.io",
      "service_test": "",
      "chainId": 2222,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2222,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ROSE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ROSE",
      "icon": "https://cryptologos.cc/logos/oasis-network-rose-logo.png",
      "name": "Oasis Emerald",
      "miniName": "ROSE",
      "unit": "ROSE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ROSE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://emerald.oasis.dev",
      "service_test": "",
      "chainId": 42262,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42262,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 3: Gaming/NFT/Ecosystem Chains ============
  CoinType.RON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "RON",
      "icon": "https://cryptologos.cc/logos/ronin-ron-logo.png",
      "name": "Ronin",
      "miniName": "RON",
      "unit": "RON",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.roninchain.com",
      "service_test": "",
      "chainId": 2020,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2020,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.IMX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IMX",
      "icon": "https://cryptologos.cc/logos/immutable-imx-logo.png",
      "name": "Immutable zkEVM",
      "miniName": "IMX",
      "unit": "IMX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IMX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.immutable.com",
      "service_test": "",
      "chainId": 13371,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 13371,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.APE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "APE",
      "icon": "https://cryptologos.cc/logos/apecoin-ape-logo.png",
      "name": "ApeChain",
      "miniName": "APE",
      "unit": "APE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "APE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.apechain.com/http",
      "service_test": "",
      "chainId": 33139,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 33139,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BONE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BONE",
      "icon": "https://cryptologos.cc/logos/shiba-inu-shib-logo.png",
      "name": "Shibarium",
      "miniName": "BONE",
      "unit": "BONE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BONE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://www.shibrpc.com",
      "service_test": "",
      "chainId": 109,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 109,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CHZ.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CHZ",
      "icon": "https://cryptologos.cc/logos/chiliz-chz-logo.png",
      "name": "Chiliz Chain",
      "miniName": "CHZ",
      "unit": "CHZ",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CHZ",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.ankr.com/chiliz",
      "service_test": "",
      "chainId": 88888,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 88888,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DOGECHAIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "DOGECHAIN",
      "icon": "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
      "name": "Dogechain",
      "miniName": "DC",
      "unit": "DOGE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DOGECHAIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.dogechain.dog",
      "service_test": "",
      "chainId": 2000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WLD.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WLD",
      "icon": "https://cryptologos.cc/logos/worldcoin-wld-logo.png",
      "name": "World Chain",
      "miniName": "WLD",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WLD",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://worldchain-mainnet.g.alchemy.com/public",
      "service_test": "",
      "chainId": 480,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 480,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 4: Bitcoin L2 Chains ============
  CoinType.RBTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "RBTC",
      "icon": "https://cryptologos.cc/logos/rsk-infrastructure-framework-rif-logo.png",
      "name": "Rootstock",
      "miniName": "RBTC",
      "unit": "RBTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RBTC",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://public-node.rsk.co",
      "service_test": "",
      "chainId": 30,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 30,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MERLIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MERLIN",
      "icon": "https://cryptologos.cc/logos/merlin-chain-merl-logo.png",
      "name": "Merlin Chain",
      "miniName": "MERL",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MERLIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.merlinchain.io",
      "service_test": "",
      "chainId": 4200,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 4200,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CORE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CORE",
      "icon": "https://cryptologos.cc/logos/core-dao-core-logo.png",
      "name": "Core DAO",
      "miniName": "CORE",
      "unit": "CORE",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CORE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.coredao.org",
      "service_test": "",
      "chainId": 1116,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1116,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BEVM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BEVM",
      "icon": "https://www.n42.ai/static/bevm.png",
      "name": "BEVM",
      "miniName": "BEVM",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BEVM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc-mainnet-1.bevm.io",
      "service_test": "",
      "chainId": 11501,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 11501,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 5: New L1/L2 Chains ============
  CoinType.BERA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BERA",
      "icon": "https://cryptologos.cc/logos/berachain-bera-logo.png",
      "name": "Berachain",
      "miniName": "BERA",
      "unit": "BERA",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BERA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.berachain.com",
      "service_test": "",
      "chainId": 80094,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 80094,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SEI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SEI",
      "icon": "https://cryptologos.cc/logos/sei-sei-logo.png",
      "name": "Sei",
      "miniName": "SEI",
      "unit": "SEI",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SEI",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm-rpc.sei-apis.com",
      "service_test": "",
      "chainId": 1329,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1329,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.PLS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "PLS",
      "icon": "https://cryptologos.cc/logos/pulsechain-pls-logo.png",
      "name": "PulseChain",
      "miniName": "PLS",
      "unit": "PLS",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "PLS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.pulsechain.com",
      "service_test": "",
      "chainId": 369,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 369,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HBAR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HBAR",
      "icon": "https://cryptologos.cc/logos/hedera-hbar-logo.png",
      "name": "Hedera",
      "miniName": "HBAR",
      "unit": "HBAR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HBAR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.hashio.io/api",
      "service_test": "",
      "chainId": 295,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 295,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FLR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FLR",
      "icon": "https://cryptologos.cc/logos/flare-flr-logo.png",
      "name": "Flare",
      "miniName": "FLR",
      "unit": "FLR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FLR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://flare-api.flare.network/ext/C/rpc",
      "service_test": "",
      "chainId": 14,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 14,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SGB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SGB",
      "icon": "https://cryptologos.cc/logos/songbird-sgb-logo.png",
      "name": "Songbird",
      "miniName": "SGB",
      "unit": "SGB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SGB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://songbird-api.flare.network/ext/C/rpc",
      "service_test": "",
      "chainId": 19,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 19,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  // ============ Batch 6: Other EVM Chains ============
  CoinType.CFX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CFX",
      "icon": "https://cryptologos.cc/logos/conflux-network-cfx-logo.png",
      "name": "Conflux eSpace",
      "miniName": "CFX",
      "unit": "CFX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CFX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.confluxrpc.com",
      "service_test": "",
      "chainId": 1030,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1030,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TLOS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TLOS",
      "icon": "https://cryptologos.cc/logos/telos-tlos-logo.png",
      "name": "Telos EVM",
      "miniName": "TLOS",
      "unit": "TLOS",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TLOS",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.telos.net/evm",
      "service_test": "",
      "chainId": 40,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 40,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ASTR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ASTR",
      "icon": "https://cryptologos.cc/logos/astar-astr-logo.png",
      "name": "Astar EVM",
      "miniName": "ASTR",
      "unit": "ASTR",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ASTR",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://evm.astar.network",
      "service_test": "",
      "chainId": 592,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 592,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BTT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BTT",
      "icon": "https://cryptologos.cc/logos/bittorrent-btt-logo.png",
      "name": "BitTorrent Chain",
      "miniName": "BTT",
      "unit": "BTT",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BTT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.bittorrentchain.io",
      "service_test": "",
      "chainId": 199,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 199,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZORA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZORA",
      "icon": "https://cryptologos.cc/logos/zora-zora-logo.png",
      "name": "Zora",
      "miniName": "ZORA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZORA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.zora.energy",
      "service_test": "",
      "chainId": 7777777,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7777777,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TAIKO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TAIKO",
      "icon": "https://cryptologos.cc/logos/taiko-taiko-logo.png",
      "name": "Taiko",
      "miniName": "TAIKO",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TAIKO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.mainnet.taiko.xyz",
      "service_test": "",
      "chainId": 167000,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 167000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OPBNB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OPBNB",
      "icon": "https://cryptologos.cc/logos/bnb-bnb-logo.png",
      "name": "opBNB",
      "miniName": "opBNB",
      "unit": "BNB",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OPBNB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://opbnb-mainnet-rpc.bnbchain.org",
      "service_test": "",
      "chainId": 204,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 204,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FRAX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FRAX",
      "icon": "https://cryptologos.cc/logos/frax-frax-logo.png",
      "name": "Fraxtal",
      "miniName": "FRAX",
      "unit": "frxETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FRAX",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.frax.com",
      "service_test": "",
      "chainId": 252,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 252,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
