import 'package:n42appv2/src/component/enums/coin_type.dart';

Map<String,dynamic> allChainUrlMap=<String,dynamic>{
  CoinType.N.name:<String,dynamic>{
    "showList":true,//主链币是否显示在主页列表中
    "isTest":false,//是否时正式链
    "supportTest":true,
    "addrType":"legacy",//地址类型
    "pathIndex":0,//path具体的账号节点
    "pathList":[0],//path数量
    "baseInfo":<String,dynamic>{
      "mKey": "N",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.N.name,
      "icon": "https://n42.ai/static/n42.png",
      "name": "N42",
      "miniName": "N",
      "unit":"N",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "http://18.170.108.78:20012",
      "service_test": "http://54.243.83.152:20012",
      "chainId": 94,//100100100,
      "chainId_test": 1142,//100100100,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    //"mainnetWS":"ws://174.129.114.74:8546",
    //"mainnetRPC":"http://174.129.114.74:8545",//"http://192.168.0.190:20012",//
    "mainnetChainID":94,//100100100,
    //"testnetWS":"ws://174.129.114.74:8546",
    //"testnetRPC":"http://174.129.114.74:8545",//"http://192.168.0.190:20012",//
    "testnetChainID":1142,
    "testnetIndex":0,//当前选择的测试网络 索引值
    "testnets":[
      {
        "testnetWS":"ws://54.175.247.94:20012",
        "testnetRPC":"http://54.243.83.152:20012",
        "testnetChainID":1142,//100100100,//
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
      "erc1155":"0x7632cA0FE8CBE97a59c600e5Afb3e75B9eC3Dc05",
      "erc721":"0xD535A5DAC95E5D5C9E121E20257E71a8FED74d95",
      "Market":"0x60a073d2F24884212859B10161590d7A67e225F9",
      "NftAddress":"0x70c8A83193a23Dd49Db33996570A573960Cf7653",//nft转账收款地址
    },
    "testnetContract":{
      "erc1155":"0xfd89417A8BE37e27162376b3a76E1EA2e1d930A9",
      "erc721":"0x1b035d6a285682De59f3b529e53D7D14b652014f",
      "Market":"0x958Bb3Fd435aC84302E8f3dE582730860825f00a",
      "NftAddress":"0xd02Da544Aa8F09F16c0FE28CA0C53772C95FB146",//nft转账收款地址
      /*"erc1155":"0x38523DAc202B9bdCe0c642E0B165F2dafe2d328c",
      "erc721":"0x1EA69cf17D3d249E545190a22213F98E47cb1379",
      "Market":"0xbA020608A5A03602d0C7D0BA64B430f1fBF65E34",*/
    },
    //挖矿合约地址
    "miningContract": "0x581231E78f9C15882ace8b6597b619999aeD5137"
  },
  CoinType.AVAX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "AVAX",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Avalanche C-Chain.png",
      "name": "Avalanche C-Chain",
      "miniName": "AVAX",
      "unit": "avax",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "AVAX",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://api.avax.network/ext/bc/C/rpc",
      "service_test": "https://api.avax-test.network/ext/bc/C/rpc",
      "chainId": 43114,
      "chainId_test": 43113,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 43114,
    "testnetChainID": 43113,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.avax-test.network/ext/bc/C/rpc",
      "testnetChainID": 43113,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BASE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BASE",
      "icon": "https://www.n42.ai/static/base.png",
      "name": "Base",
      "miniName": "BASE",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BASE",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://endpoints.omniatech.io/v1/base/mainnet/public",
      "service_test": "",
      "chainId": 8453,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 8453,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BNB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BNB",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Binance Smart Chain.png",
      "name": "Binance Smart Chain",
      "miniName": "BNB",
      "unit": "bnb",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BNB",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://bsc-dataseed1.binance.org/",
      "service_test": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "chainId": 56,
      "chainId_test": 97,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "BEP20"
    },
    "mainnetChainID": 56,
    "testnetChainID": 97,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "testnetChainID": 97,
      "testnetContract":<String,dynamic> {}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "BTC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Bitcoin.png",
      "name": "Bitcoin",
      "miniName": "BTC",
      "unit": "btc",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BTC",
      "path": {
        "segwit": "m/84'/0'/0'/0/0",
        "legacy": "m/44'/0'/0'/0/0",
        "taproot":"m/86'/0'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BOBA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BOBA",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Boba Network.png",
      "name": "Boba Network",
      "miniName": "BOBA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BOBA",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.boba.network",
      "service_test": "https://rinkeby.boba.network/",
      "chainId": 288,
      "chainId_test": 28,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 288,
    "testnetChainID": 28,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rinkeby.boba.network/",
      "testnetChainID": 28,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CELO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CELO",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Celo.png",
      "name": "Celo",
      "miniName": "CELO",
      "unit": "celo",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CELO",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://forno.celo.org/",
      "service_test": "https://alfajores-forno.celo-testnet.org",
      "chainId": 42220,
      "chainId_test": 44787,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 42220,
    "testnetChainID": 44787,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://alfajores-forno.celo-testnet.org",
      "testnetChainID": 44787,
      "testnetContract": {}
    }],
    "mainnets": {},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DASH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DASH",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Dash.png",
      "name": "Dash",
      "miniName": "DASH",
      "unit": "dash",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DASH",
      "path": {
        "legacy": "m/44'/5'/0'/0/0"
      },
      "service": "",
      "service_test": "http://seed-1.testnet.networks.dash.org:3000/",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "http://seed-1.testnet.networks.dash.org:3000/",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DOGE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DOGE",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Dogecoin.png",
      "name": "Dogecoin",
      "miniName": "DOGE",
      "unit": "doge",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DOGE",
      "path": {
        "legacy": "m/44'/3'/0'/0/0"
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ETH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ETH",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Ethereum.png",
      "name": "Ethereum",
      "miniName": "ETH",
      "unit": "eth",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ETH",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "service_test": "https://ropsten.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "chainId": 1,
      "chainId_test": 3,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1,
    "testnetChainID": 3,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://ropsten.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "testnetChainID": 3,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ETC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ETC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Ethereum Classic.png",
      "name": "Ethereum Classic",
      "miniName": "ETC",
      "unit": "etc",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ETC",
      "path": {
        "legacy": "m/44'/61'/0'/0/0"
      },
      "service": "https://etc.rivet.link",
      "service_test": "https://rpc.mordor.etccooperative.org/",
      "chainId": 61,
      "chainId_test": 6,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 61,
    "testnetChainID": 6,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc.mordor.etccooperative.org/",
      "testnetChainID": 6,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FTM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "FTM",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Fantom.png",
      "name": "Fantom",
      "miniName": "FTM",
      "unit": "ftm",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FTM",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.ankr.com/fantom/",
      "service_test": "https://rpc.testnet.fantom.network",
      "chainId": 250,
      "chainId_test": 4002,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 250,
    "testnetChainID": 4002,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc.testnet.fantom.network",
      "testnetChainID": 4002,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GO",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/GoChain.png",
      "name": "GoChain",
      "miniName": "GO",
      "unit": "go",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GO",
      "path": {
        "legacy": "m/44'/6060'/0'/0/0"
      },
      "service": "https://rpc.gochain.io",
      "service_test": "https://testnet-rpc.gochain.io",
      "chainId": 60,
      "chainId_test": 31337,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 60,
    "testnetChainID": 31337,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://testnet-rpc.gochain.io",
      "testnetChainID": 31337,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Huobi ECO Chain.png",
      "name": "Huobi ECO Chain",
      "miniName": "HT",
      "unit": "ht",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HT",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://http-mainnet.hecochain.com",
      "service_test": "https://http-testnet.hecochain.com",
      "chainId": 128,
      "chainId_test": 256,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 128,
    "testnetChainID": 256,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://http-testnet.hecochain.com",
      "testnetChainID": 256,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KLAY.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KLAY",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Klaytn.png",
      "name": "Klaytn",
      "miniName": "KLAY",
      "unit": "klay",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KLAY",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://klaytn.blockpi.network/v1/rpc/public",
      "service_test": "https://api.baobab.klaytn.net:8651",
      "chainId": 8217,
      "chainId_test": 1001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 8217,
    "testnetChainID": 1001,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.baobab.klaytn.net:8651",
      "testnetChainID": 1001,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KCS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KCS",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/KuCoin Community Chain.png",
      "name": "KuCoin Community Chain",
      "miniName": "KCS",
      "unit": "kcs",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KCS",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc-mainnet.kcc.network",
      "service_test": "https://rpc-testnet.kcc.network",
      "chainId": 321,
      "chainId_test": 322,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 321,
    "testnetChainID": 322,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpc-testnet.kcc.network",
      "testnetChainID": 322,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LTC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "LTC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Litecoin.png",
      "name": "Litecoin",
      "miniName": "LTC",
      "unit": "ltc",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LTC",
      "path": {
        "segwit": "m/84'/2'/0'/0/0",
        "legacy": "m/44'/2'/0'/0/0"
      },
      "service": "",
      "service_test": "",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MTR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MTR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Meter.png",
      "name": "Meter",
      "miniName": "MTR",
      "unit": "mtr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MTR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.meter.io",
      "service_test": "https://rpctest.meter.io",
      "chainId": 82,
      "chainId_test": 83,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 82,
    "testnetChainID": 83,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://rpctest.meter.io",
      "testnetChainID": 83,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.METIS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "METIS",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Metis.png",
      "name": "Metis",
      "miniName": "METIS",
      "unit": "metis",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "METIS",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://andromeda.metis.io/?owner=1088",
      "service_test": "https://stardust.metis.io/?owner=588",
      "chainId": 1088,
      "chainId_test": 588,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1088,
    "testnetChainID": 588,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://stardust.metis.io/?owner=588",
      "testnetChainID": 588,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GLMR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "GLMR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Moonbeam.png",
      "name": "Moonbeam",
      "miniName": "GLMR",
      "unit": "glmr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GLMR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://rpc.api.moonbeam.network",
      "service_test": "https://moonbase-alpha.public.blastapi.io/",
      "chainId": 1284,
      "chainId_test": 1287,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1284,
    "testnetChainID": 1287,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://moonbase-alpha.public.blastapi.io/",
      "testnetChainID": 1287,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MOVR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MOVR",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Moonriver.png",
      "name": "Moonriver",
      "miniName": "MOVR",
      "unit": "movr",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MOVR",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://moonriver.public.blastapi.io",
      "service_test": "",
      "chainId": 1285,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1285,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OKT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OKT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/OKX Chain.png",
      "name": "OKX Chain",
      "miniName": "OKT",
      "unit": "okt",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OKT",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://exchainrpc.okex.org",
      "service_test": "https://exchaintestrpc.okex.org",
      "chainId": 66,
      "chainId_test": 65,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 66,
    "testnetChainID": 65,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://exchaintestrpc.okex.org",
      "testnetChainID": 65,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OP.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "OP",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Optimism Ethereum.png",
      "name": "Optimism Ethereum",
      "miniName": "OP",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OP",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://mainnet.optimism.io",
      "service_test": "https://kovan.optimism.io/",
      "chainId": 10,
      "chainId_test": 69,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 10,
    "testnetChainID": 69,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://kovan.optimism.io/",
      "testnetChainID": 69,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MATIC.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MATIC",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Polygon.png",
      "name": "Polygon",
      "miniName": "MATIC",
      "unit": "matic",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MATIC",
      "path": {
        "legacy": "m/44'/60'/0'/0/0"
      },
      "service": "https://polygon-rpc.com/",
      "service_test": "https://matic-mumbai.chainstacklabs.com",
      "chainId": 137,
      "chainId_test": 80001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 137,
    "testnetChainID": 80001,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://matic-mumbai.chainstacklabs.com",
      "testnetChainID": 80001,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SOL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Solana",
      "coinType": "SOL",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Solana.png",
      "name": "Solana",
      "miniName": "SOL",
      "unit": "sol",
      "decimals": 9,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SOL",
      "path": {
        "legacy": "m/44'/501'/0'"
      },
      "service": "https://api.mainnet-beta.solana.com",
      "service_test": "http://api.testnet.solana.com",
      "chainId": 0,
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "SPL"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "http://api.testnet.solana.com",
      "testnetChainID": 0,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TT",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Thunder Token.png",
      "name": "Thunder Token",
      "miniName": "TT",
      "unit": "tt",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TT",
      "path": {
        "legacy": "m/44'/1001'/0'/0/0"
      },
      "service": "https://mainnet-rpc.thundercore.com",
      "service_test": "https://testnet-rpc.thundercore.com",
      "chainId": 108,
      "chainId_test": 18,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 108,
    "testnetChainID": 18,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://testnet-rpc.thundercore.com",
      "testnetChainID": 18,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TRX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Tron",
      "coinType": "TRX",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Tron.png",
      "name": "Tron",
      "miniName": "TRX",
      "unit": "trx",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TRX",
      "path": {
        "legacy": "m/44'/195'/0'/0/0"
      },
      "service": "https://api.trongrid.io",
      "service_test": "https://api.shasta.trongrid.io",
      "chainId": 728126428,
      "chainId_test": 2494104990,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "TRC20"
    },
    "mainnetChainID": 728126428,
    "testnetChainID": 2494104990,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://api.shasta.trongrid.io",
      "testnetChainID": 2494104990,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WAN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WAN",
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/wanChain.png",
      "name": "wanChain",
      "miniName": "WAN",
      "unit": "wan",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WAN",
      "path": {
        "legacy": "m/44'/5718350'/0'/0/0"
      },
      "service": "https://gwan-ssl.wandevs.org:56891",
      "service_test": "https://gwan-ssl.wandevs.org:46891/",
      "chainId": 888,
      "chainId_test": 999,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 888,
    "testnetChainID": 999,
    "testnetIndex": 0,
    "testnets": [{
      "testnetWS": "",
      "testnetRPC": "https://gwan-ssl.wandevs.org:46891/",
      "testnetChainID": 999,
      "testnetContract": <String,dynamic>{}
    }],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
