import 'package:n42_wallet/src/component/enums/coin_type.dart';

final Map<String, dynamic> chainDataPart5 = <String, dynamic>{
  CoinType.WORLD.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "WORLD",
      "icon": "https://cryptologos.cc/logos/worldcoin-wld-logo.png",
      "name": "World Chain",
      "miniName": "WLD",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WORLD",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://worldchain-mainnet.g.alchemy.com/public",
      "service_test": "",
      "chainId": 480,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 480,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.INK2.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "INK2",
      "icon": "https://cryptologos.cc/logos/ink-logo.png",
      "name": "Ink",
      "miniName": "INK",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "INK2",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc-gel.inkonchain.com",
      "service_test": "",
      "chainId": 57073,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 57073,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.APECHAIN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "APECHAIN",
      "icon": "https://cryptologos.cc/logos/apecoin-ape-logo.png",
      "name": "ApeChain",
      "miniName": "APE",
      "unit": "APE",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "APECHAIN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.apechain.com/http",
      "service_test": "",
      "chainId": 33139,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 33139,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Phase 2: Cosmos ecosystem chains
  CoinType.INJ.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "INJ",
      "icon": "https://cryptologos.cc/logos/injective-inj-logo.png",
      "name": "Injective",
      "miniName": "INJ",
      "unit": "INJ",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "INJ",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://sentry.lcd.injective.network",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "inj"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TIA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "TIA",
      "icon": "https://cryptologos.cc/logos/celestia-tia-logo.png",
      "name": "Celestia",
      "miniName": "TIA",
      "unit": "TIA",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TIA",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://celestia-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "celestia"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DYDX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "DYDX",
      "icon": "https://cryptologos.cc/logos/dydx-dydx-logo.png",
      "name": "dYdX",
      "miniName": "DYDX",
      "unit": "DYDX",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DYDX",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://dydx-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "dydx"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.OSMO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "OSMO",
      "icon": "https://cryptologos.cc/logos/osmosis-osmo-logo.png",
      "name": "Osmosis",
      "miniName": "OSMO",
      "unit": "OSMO",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "OSMO",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://osmosis-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "osmo"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.AKT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "AKT",
      "icon": "https://cryptologos.cc/logos/akash-network-akt-logo.png",
      "name": "Akash",
      "miniName": "AKT",
      "unit": "AKT",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "AKT",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://akash-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "akash"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NTRN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "NTRN",
      "icon": "https://cryptologos.cc/logos/neutron-ntrn-logo.png",
      "name": "Neutron",
      "miniName": "NTRN",
      "unit": "NTRN",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NTRN",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://neutron-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "neutron"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SCRT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "SCRT",
      "icon": "https://cryptologos.cc/logos/secret-scrt-logo.png",
      "name": "Secret Network",
      "miniName": "SCRT",
      "unit": "SCRT",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SCRT",
      "path": {"legacy": "m/44'/529'/0'/0/0"},
      "service": "https://secret-4.api.trivium.network:1317",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "SNIP-20",
      "bech32Prefix": "secret"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.STRD.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "STRD",
      "icon": "https://cryptologos.cc/logos/stride-strd-logo.png",
      "name": "Stride",
      "miniName": "STRD",
      "unit": "STRD",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "STRD",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://stride-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "stride"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.JUNO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "JUNO",
      "icon": "https://cryptologos.cc/logos/juno-juno-logo.png",
      "name": "Juno",
      "miniName": "JUNO",
      "unit": "JUNO",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "JUNO",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://juno-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "CW20",
      "bech32Prefix": "juno"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KUJI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "KUJI",
      "icon": "https://cryptologos.cc/logos/kujira-kuji-logo.png",
      "name": "Kujira",
      "miniName": "KUJI",
      "unit": "KUJI",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KUJI",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://kujira-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "kujira"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XPRT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "XPRT",
      "icon": "https://cryptologos.cc/logos/persistence-xprt-logo.png",
      "name": "Persistence",
      "miniName": "XPRT",
      "unit": "XPRT",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XPRT",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://persistence-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "persistence"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.RUNE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "RUNE",
      "icon": "https://cryptologos.cc/logos/thorchain-rune-logo.png",
      "name": "THORChain",
      "miniName": "RUNE",
      "unit": "RUNE",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RUNE",
      "path": {"legacy": "m/44'/931'/0'/0/0"},
      "service": "https://thornode.ninerealms.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "thor"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KAVA2.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "KAVA2",
      "icon": "https://cryptologos.cc/logos/kava-kava-logo.png",
      "name": "Kava Cosmos",
      "miniName": "KAVA",
      "unit": "KAVA",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KAVA2",
      "path": {"legacy": "m/44'/459'/0'/0/0"},
      "service": "https://kava-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "kava"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CRE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "CRE",
      "icon": "https://cryptologos.cc/logos/crescent-cre-logo.png",
      "name": "Crescent",
      "miniName": "CRE",
      "unit": "CRE",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CRE",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://crescent-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "cre"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SOMM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "SOMM",
      "icon": "https://cryptologos.cc/logos/sommelier-somm-logo.png",
      "name": "Sommelier",
      "miniName": "SOMM",
      "unit": "SOMM",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SOMM",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://sommelier-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "somm"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MARS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "MARS",
      "icon": "https://cryptologos.cc/logos/mars-protocol-mars-logo.png",
      "name": "Mars Protocol",
      "miniName": "MARS",
      "unit": "MARS",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MARS",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://mars-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "mars"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CMDX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "CMDX",
      "icon": "https://cryptologos.cc/logos/comdex-cmdx-logo.png",
      "name": "Comdex",
      "miniName": "CMDX",
      "unit": "CMDX",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CMDX",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://comdex-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "",
      "bech32Prefix": "comdex"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Phase 3: ZK/unique architecture chains
  CoinType.STRK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Starknet",
      "coinType": "STRK",
      "icon": "https://cryptologos.cc/logos/starknet-strk-logo.png",
      "name": "Starknet",
      "miniName": "STRK",
      "unit": "STRK",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "STRK",
      "path": {"legacy": "m/44'/9004'/0'/0/0"},
      "service": "https://starknet-mainnet.public.blastapi.io",
      "service_test": "https://starknet-sepolia.public.blastapi.io",
      "chainId": "23448594291968334",
      "chainId_test": "1536727068981429685",
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
      "starknetChainId": "SN_MAIN",
      "starknetChainId_test": "SN_SEPOLIA"
    },
    "mainnetChainID": "23448594291968334",
    "testnetChainID": "1536727068981429685",
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://starknet-sepolia.public.blastapi.io", "testnetChainID": "1536727068981429685", "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Phase 4: Other important chains
  CoinType.EOS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "EOSIO",
      "coinType": "EOS",
      "icon": "https://cryptologos.cc/logos/eos-eos-logo.png",
      "name": "EOS",
      "miniName": "EOS",
      "unit": "EOS",
      "decimals": 4,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EOS",
      "path": {"legacy": "m/44'/194'/0'/0/0"},
      "service": "https://eos.greymass.com",
      "service_test": "https://jungle4.greymass.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://jungle4.greymass.com", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WAX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "EOSIO",
      "coinType": "WAX",
      "icon": "https://cryptologos.cc/logos/wax-waxp-logo.png",
      "name": "WAX",
      "miniName": "WAX",
      "unit": "WAX",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WAX",
      "path": {"legacy": "m/44'/14001'/0'/0/0"},
      "service": "https://wax.greymass.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.WAVES.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Waves",
      "coinType": "WAVES",
      "icon": "https://cryptologos.cc/logos/waves-waves-logo.png",
      "name": "Waves",
      "miniName": "WAVES",
      "unit": "WAVES",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "WAVES",
      "path": {"legacy": "m/44'/5741564'/0'/0/0"},
      "service": "https://nodes.wavesnodes.com",
      "service_test": "https://nodes-testnet.wavesnodes.com",
      "chainId": 87,
      "chainId_test": 84,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 87,
    "testnetChainID": 84,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://nodes-testnet.wavesnodes.com", "testnetChainID": 84, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NEO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Neo",
      "coinType": "NEO",
      "icon": "https://cryptologos.cc/logos/neo-neo-logo.png",
      "name": "NEO",
      "miniName": "NEO",
      "unit": "NEO",
      "decimals": 0,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NEO",
      "path": {"legacy": "m/44'/888'/0'/0/0"},
      "service": "https://mainnet1.neo.coz.io:443",
      "service_test": "https://testnet1.neo.coz.io:443",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://testnet1.neo.coz.io:443", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.GAS.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Neo",
      "coinType": "GAS",
      "icon": "https://cryptologos.cc/logos/gas-gas-logo.png",
      "name": "GAS",
      "miniName": "GAS",
      "unit": "GAS",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "GAS",
      "path": {"legacy": "m/44'/888'/0'/0/0"},
      "service": "https://mainnet1.neo.coz.io:443",
      "service_test": "https://testnet1.neo.coz.io:443",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://testnet1.neo.coz.io:443", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ONT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ontology",
      "coinType": "ONT",
      "icon": "https://cryptologos.cc/logos/ontology-ont-logo.png",
      "name": "Ontology",
      "miniName": "ONT",
      "unit": "ONT",
      "decimals": 0,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ONT",
      "path": {"legacy": "m/44'/1024'/0'/0/0"},
      "service": "https://dappnode1.ont.io:10334",
      "service_test": "https://polaris1.ont.io:10334",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://polaris1.ont.io:10334", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ONG.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ontology",
      "coinType": "ONG",
      "icon": "https://cryptologos.cc/logos/ontology-gas-ong-logo.png",
      "name": "Ontology Gas",
      "miniName": "ONG",
      "unit": "ONG",
      "decimals": 9,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ONG",
      "path": {"legacy": "m/44'/1024'/0'/0/0"},
      "service": "https://dappnode1.ont.io:10334",
      "service_test": "https://polaris1.ont.io:10334",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://polaris1.ont.io:10334", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZEN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "ZEN",
      "icon": "https://cryptologos.cc/logos/horizen-zen-logo.png",
      "name": "Horizen",
      "miniName": "ZEN",
      "unit": "ZEN",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZEN",
      "path": {"legacy": "m/44'/121'/0'/0/0"},
      "service": "https://explorer.horizen.io/api",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DCR.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Decred",
      "coinType": "DCR",
      "icon": "https://cryptologos.cc/logos/decred-dcr-logo.png",
      "name": "Decred",
      "miniName": "DCR",
      "unit": "DCR",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DCR",
      "path": {"legacy": "m/44'/42'/0'/0/0"},
      "service": "https://mainnet.decred.org/api",
      "service_test": "https://testnet.decred.org/api",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://testnet.decred.org/api", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XEM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "NEM",
      "coinType": "XEM",
      "icon": "https://cryptologos.cc/logos/nem-xem-logo.png",
      "name": "NEM",
      "miniName": "XEM",
      "unit": "XEM",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XEM",
      "path": {"legacy": "m/44'/43'/0'/0/0"},
      "service": "https://nemesis.xem.io:7891",
      "service_test": "https://test-nemesis.xem.io:7891",
      "chainId": 104,
      "chainId_test": -104,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 104,
    "testnetChainID": -104,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://test-nemesis.xem.io:7891", "testnetChainID": -104, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XYM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "NEM",
      "coinType": "XYM",
      "icon": "https://cryptologos.cc/logos/symbol-xym-logo.png",
      "name": "Symbol",
      "miniName": "XYM",
      "unit": "XYM",
      "decimals": 6,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XYM",
      "path": {"legacy": "m/44'/4343'/0'/0/0"},
      "service": "https://sym-main.opening-line.jp:3001",
      "service_test": "https://sym-test.opening-line.jp:3001",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://sym-test.opening-line.jp:3001", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.IOST.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "IOST",
      "coinType": "IOST",
      "icon": "https://cryptologos.cc/logos/iost-iost-logo.png",
      "name": "IOST",
      "miniName": "IOST",
      "unit": "IOST",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IOST",
      "path": {"legacy": "m/44'/291'/0'/0/0"},
      "service": "https://api.iost.io",
      "service_test": "https://test.api.iost.io",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://test.api.iost.io", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ICX.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "ICON",
      "coinType": "ICX",
      "icon": "https://cryptologos.cc/logos/icon-icx-logo.png",
      "name": "ICON",
      "miniName": "ICX",
      "unit": "ICX",
      "decimals": 18,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ICX",
      "path": {"legacy": "m/44'/74'/0'/0/0"},
      "service": "https://ctz.solidwallet.io/api/v3",
      "service_test": "https://sejong.net.solidwallet.io/api/v3",
      "chainId": 1,
      "chainId_test": 83,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 1,
    "testnetChainID": 83,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://sejong.net.solidwallet.io/api/v3", "testnetChainID": 83, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.NANO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Nano",
      "coinType": "NANO",
      "icon": "https://cryptologos.cc/logos/nano-nano-logo.png",
      "name": "Nano",
      "miniName": "NANO",
      "unit": "NANO",
      "decimals": 30,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "NANO",
      "path": {"legacy": "m/44'/165'/0'/0/0"},
      "service": "https://proxy.nanos.cc/proxy",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ARK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ark",
      "coinType": "ARK",
      "icon": "https://cryptologos.cc/logos/ark-ark-logo.png",
      "name": "Ark",
      "miniName": "ARK",
      "unit": "ARK",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ARK",
      "path": {"legacy": "m/44'/111'/0'/0/0"},
      "service": "https://api.ark.io/api",
      "service_test": "https://dapi.ark.io/api",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://dapi.ark.io/api", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.QTUM2.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Qtum",
      "coinType": "QTUM2",
      "icon": "https://cryptologos.cc/logos/qtum-qtum-logo.png",
      "name": "Qtum",
      "miniName": "QTUM",
      "unit": "QTUM",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "QTUM",
      "path": {"legacy": "m/44'/2301'/0'/0/0"},
      "service": "https://qtum.info/api",
      "service_test": "https://testnet.qtum.info/api",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://testnet.qtum.info/api", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.HIVE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Hive",
      "coinType": "HIVE",
      "icon": "https://cryptologos.cc/logos/hive-blockchain-hive-logo.png",
      "name": "Hive",
      "miniName": "HIVE",
      "unit": "HIVE",
      "decimals": 3,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HIVE",
      "path": {"legacy": "m/44'/397'/0'/0/0"},
      "service": "https://api.hive.blog",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.STEEM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Hive",
      "coinType": "STEEM",
      "icon": "https://cryptologos.cc/logos/steem-steem-logo.png",
      "name": "Steem",
      "miniName": "STEEM",
      "unit": "STEEM",
      "decimals": 3,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "STEEM",
      "path": {"legacy": "m/44'/135'/0'/0/0"},
      "service": "https://api.steemit.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LSK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": true,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "LSK",
      "icon": "https://cryptologos.cc/logos/lisk-lsk-logo.png",
      "name": "Lisk",
      "miniName": "LSK",
      "unit": "LSK",
      "decimals": 8,
      "balance": "0",
      "balance_test": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LSK",
      "path": {"legacy": "m/44'/134'/0'/0/0"},
      "service": "https://service.lisk.com/api/v3",
      "service_test": "https://testnet-service.lisk.com/api/v3",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "https://testnet-service.lisk.com/api/v3", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
