//walletList中使用 - Part 2: ALGO, XTZ, LTC, DOGE, ETC, FTM, CRO, KLAY, ZKSYNC, LINEA, SCROLL, MNT, BLAST, NEAR, ZIL, GNOSIS, NOVA
import 'package:n42appv2/src/component/enums/coin_type.dart';

Map<String,dynamic> chainUrlDataPart2={
  CoinType.ALGO.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Algorand.name,
      "coinType": CoinType.ALGO.name,
      "icon": "https://cryptologos.cc/logos/algorand-algo-logo.png",
      "name": "Algorand",
      "miniName": "ALGO",
      "unit":"ALGO",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ALGO",
      "path": {
        "legacy":"m/44'/283'/0'/0'/0'",
      },
      "service": "https://mainnet-api.algonode.cloud",
      "service_test": "https://testnet-api.algonode.cloud",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ALGO",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://testnet-api.algonode.cloud","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 20. XTZ - Tezos
  CoinType.XTZ.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Tezos.name,
      "coinType": CoinType.XTZ.name,
      "icon": "https://cryptologos.cc/logos/tezos-xtz-logo.png",
      "name": "Tezos",
      "miniName": "XTZ",
      "unit":"XTZ",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "XTZ",
      "path": {
        "legacy":"m/44'/1729'/0'/0'",
      },
      "service": "https://mainnet.api.tez.ie",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XTZ",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 21. LTC - Litecoin
  CoinType.LTC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"segwit",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.LTC.name,
      "icon": "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
      "name": "Litecoin",
      "miniName": "LTC",
      "unit":"LTC",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "LTC",
      "path": {
        "legacy":"m/44'/2'/0'/0/0",
        "segwit":"m/84'/2'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 22. DOGE - Dogecoin
  CoinType.DOGE.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.DOGE.name,
      "icon": "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
      "name": "Dogecoin",
      "miniName": "DOGE",
      "unit":"DOGE",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "DOGE",
      "path": {
        "legacy":"m/44'/3'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 23. ETC - Ethereum Classic
  CoinType.ETC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ETC.name,
      "icon": "https://cryptologos.cc/logos/ethereum-classic-etc-logo.png",
      "name": "Ethereum Classic",
      "miniName": "ETC",
      "unit":"ETC",
      "chainId": 61,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ETC",
      "path": {
        "legacy":"m/44'/61'/0'/0/0",
      },
      "service": "https://etc.rivet.link",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":61,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 24. FTM - Fantom
  CoinType.FTM.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.FTM.name,
      "icon": "https://cryptologos.cc/logos/fantom-ftm-logo.png",
      "name": "Fantom",
      "miniName": "FTM",
      "unit":"FTM",
      "chainId": 250,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "FTM",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.ftm.tools",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":250,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 25. CRO - Cronos
  CoinType.CRO.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.CRO.name,
      "icon": "https://cryptologos.cc/logos/cronos-cro-logo.png",
      "name": "Cronos",
      "miniName": "CRO",
      "unit":"CRO",
      "chainId": 25,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "CRO",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://evm.cronos.org",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":25,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 26. KLAY - Klaytn
  CoinType.KLAY.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.KLAY.name,
      "icon": "https://cryptologos.cc/logos/klaytn-klay-logo.png",
      "name": "Klaytn",
      "miniName": "KLAY",
      "unit":"KLAY",
      "chainId": 8217,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "KLAY",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://public-en-cypress.klaytn.net",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":8217,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 27. ZKSYNC - zkSync Era (热门L2)
  CoinType.ZKSYNC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ZKSYNC.name,
      "icon": "https://cryptologos.cc/logos/zksync-zk-logo.png",
      "name": "zkSync Era",
      "miniName": "ZK",
      "unit":"ETH",
      "chainId": 324,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ZKSYNC",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.era.zksync.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":324,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 28. LINEA - Linea (热门L2)
  CoinType.LINEA.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.LINEA.name,
      "icon": "https://cryptologos.cc/logos/linea-linea-logo.png",
      "name": "Linea",
      "miniName": "LINEA",
      "unit":"ETH",
      "chainId": 59144,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "LINEA",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.linea.build",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":59144,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 29. SCROLL - Scroll (热门L2)
  CoinType.SCROLL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.SCROLL.name,
      "icon": "https://cryptologos.cc/logos/scroll-scr-logo.png",
      "name": "Scroll",
      "miniName": "SCROLL",
      "unit":"ETH",
      "chainId": 534352,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SCROLL",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.scroll.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":534352,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 30. MNT - Mantle
  CoinType.MNT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.MNT.name,
      "icon": "https://cryptologos.cc/logos/mantle-mnt-logo.png",
      "name": "Mantle",
      "miniName": "MNT",
      "unit":"MNT",
      "chainId": 5000,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "MNT",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.mantle.xyz",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":5000,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 31. BLAST - Blast
  CoinType.BLAST.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BLAST.name,
      "icon": "https://cryptologos.cc/logos/blast-blast-logo.png",
      "name": "Blast",
      "miniName": "BLAST",
      "unit":"ETH",
      "chainId": 81457,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BLAST",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.blast.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":81457,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 32. NEAR - Near Protocol
  CoinType.NEAR.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Near.name,
      "coinType": CoinType.NEAR.name,
      "icon": "https://cryptologos.cc/logos/near-protocol-near-logo.png",
      "name": "NEAR Protocol",
      "miniName": "NEAR",
      "unit":"NEAR",
      "chainId": 0,
      "decimals": 24,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "NEAR",
      "path": {
        "legacy":"m/44'/397'/0'",
      },
      "service": "https://rpc.mainnet.near.org",
      "service_test": "https://rpc.testnet.near.org",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "NEAR",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://rpc.testnet.near.org","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 33. ZIL - Zilliqa
  CoinType.ZIL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Zilliqa.name,
      "coinType": CoinType.ZIL.name,
      "icon": "https://cryptologos.cc/logos/zilliqa-zil-logo.png",
      "name": "Zilliqa",
      "miniName": "ZIL",
      "unit":"ZIL",
      "chainId": 0,
      "decimals": 12,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ZIL",
      "path": {
        "legacy":"m/44'/313'/0'/0'/0'",
      },
      "service": "https://api.zilliqa.com",
      "service_test": "https://dev-api.zilliqa.com",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ZIL",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://dev-api.zilliqa.com","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 34. GNOSIS - Gnosis Chain (原xDAI)
  CoinType.GNOSIS.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.GNOSIS.name,
      "icon": "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png",
      "name": "Gnosis Chain",
      "miniName": "xDAI",
      "unit":"xDAI",
      "chainId": 100,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "GNOSIS",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.gnosischain.com",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":100,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 35. NOVA - Arbitrum Nova
  CoinType.NOVA.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.NOVA.name,
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum Nova",
      "miniName": "NOVA",
      "unit":"ETH",
      "chainId": 42170,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "NOVA",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://nova.arbitrum.io/rpc",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":42170,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },
};
