//walletList中使用
import 'package:n42appv2/src/component/enums/coin_type.dart';
import 'package:decimal/decimal.dart';
import 'package:wallet/wallet.dart';

/// 默认钱包链配置
/// 排序原则：N42主链放首位，其余按知名度和常用程度排列
/// 2026年调整：移除OKT、ZIL等低知名度链，添加ARB、OP、AVAX、MATIC、TON等热门链
Map<String,dynamic> chainUrlMap={
  // 1. N42 - 主链币，放首位
  CoinType.N.name:<String,dynamic>{
    "showList":true,//主链币是否显示在主页列表中
    "isTest":true,//是否时正式链
    "supportTest":true,
    "addrType":"legacy",//地址类型
    "pathIndex":0,//path具体的账号节点
    "pathList":[0],//path数量
    "baseInfo":<String,dynamic>{
      "mKey": "N",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.N.name,
      "icon": "https://n42.ai/static/n42.png",
      "name": "N42",
      "miniName": "N",
      "unit":"N",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.n42.world",
      "service_test": "http://5.161.252.59:8545",
      "chainId": 94,
      "chainId_test": 1142,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":94,
    "testnetChainID":1142,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"ws://54.175.247.94:20012",
        "testnetRPC":"http://5.161.252.59:8545",
        "testnetChainID":1142,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
      "erc1155":"0x7632cA0FE8CBE97a59c600e5Afb3e75B9eC3Dc05",
      "erc721":"0xD535A5DAC95E5D5C9E121E20257E71a8FED74d95",
      "Market":"0x60a073d2F24884212859B10161590d7A67e225F9",
      "NftAddress":"0x70c8A83193a23Dd49Db33996570A573960Cf7653",
    },
    "testnetContract":{
      "erc1155":"0xfd89417A8BE37e27162376b3a76E1EA2e1d930A9",
      "erc721":"0x1b035d6a285682De59f3b529e53D7D14b652014f",
      "Market":"0x958Bb3Fd435aC84302E8f3dE582730860825f00a",
      "NftAddress":"0xd02Da544Aa8F09F16c0FE28CA0C53772C95FB146",
    },
    "miningContract": "0x581231E78f9C15882ace8b6597b619999aeD5137"
  },

  // 2. BTC - Bitcoin（最知名加密货币）
  CoinType.BTC.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"segwit",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.BTC.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Bitcoin.png",
      "name": "Bitcoin",
      "miniName": "BTC",
      "unit":"BTC",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BTC",
      "path": {
        "legacy":"m/44'/0'/0'/0/0",
        "segwit":"m/84'/1'/0'/0/0",
        "taproot":"m/86'/0'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{
    },
    "testnetContract":{},
  },

  // 3. ETH - Ethereum（第二大加密货币）
  CoinType.ETH.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "mKey": "ETH",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ETH.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Ethereum.png",
      "name": "Ethereum",
      "miniName": "ETH",
      "unit":"ETH",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.infura.io/v3/b6bd1324a1b34545b1fdda886dd494f9",
      "service_test": "https://eth-sepolia.public.blastapi.io",
      "chainId": 1,
      "chainId_test": 11155111,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":1,
    "testnetChainID":3,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://eth-sepolia.public.blastapi.io",
        "testnetRPC":"https://eth-sepolia.public.blastapi.io",
        "testnetChainID":11155111,
        "testnetContract":<String,dynamic>{
          "0X6C30A50430CC615C4659DF2DBE3E42036583BE7E":<String,dynamic>{
            "mKey": "0X6C30A50430CC615C4659DF2DBE3E42036583BE7E",
            "blockchainType": BlockchainType.Ethereum.name,
            "coinType": CoinType.ETH.name,
            "icon": "https://api.astranet.app/market/v1/r/coinImage/vbtc.png",
            "name": "vBTC",
            "miniName": "vBTC",
            "unit":"vBTC",
            "decimals": 8,
            "balance":"0",
            "balance_test":"0",
            "coinPrice":0.0,
            "percentage":0.0,
            "isContract": true,
            "path": {
              "legacy":"m/44'/60'/0'/0/0",
            },
            "service": "http://18.170.108.78:20012",
            "service_test": "https://eth-sepolia.public.blastapi.io",
            "chainId": 1,
            "chainId_test": 11155111,
            "contract": "0x6c30A50430cC615C4659DF2dBe3E42036583bE7E",
            "contract_test": "0x6c30A50430cC615C4659DF2dBe3E42036583bE7E",
            "canEdit": false,
            "rules": "ERC20",
            "customer":false,
          }
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
  },

  // 4. SOL - Solana（高性能公链，热门）
  CoinType.SOL.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Solana.name,
      "coinType": CoinType.SOL.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Solana.png",
      "name": "Solana",
      "miniName": "SOL",
      "unit":"SOL",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SOL",
      "path": {
        "legacy":"m/44'/501'/0'",
      },
      "service": "https://api.mainnet-beta.solana.com",
      "service_test": "https://api.testnet.solana.com",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "SPL",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
      "SOL":"7ViD4q77VfADUiE2euhBVmrvYrrMJW3bFbjcgvujmAyZ",
    },
  },

  // 5. BNB - Binance Smart Chain（交易所生态，热门）
  CoinType.BNB.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BNB.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/BNB.png",
      "name": "Binance Smart Chain",
      "miniName": "BNB",
      "unit":"BNB",
      "chainId": 56,
      "decimals": 18,
      "balance":'0',
      "balance_test":'0',
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BNB",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://bsc-dataseed1.binance.org/",
      "service_test": "https://data-seed-prebsc-1-s1.binance.org:8545",
      "chainId_test": 97,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "BEP20",
    },
    "mainnetWS":"https://bsc-dataseed1.binance.org",
    "mainnetRPC":"https://bsc-dataseed1.binance.org",
    "mainnetChainID":0,
    "testnetWS":"https://data-seed-prebsc-1-s1.binance.org:8545",
    "testnetRPC":"https://data-seed-prebsc-1-s1.binance.org:8545",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://data-seed-prebsc-1-s1.binance.org:8545",
        "testnetRPC":"https://data-seed-prebsc-1-s1.binance.org:8545",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 6. ARB - Arbitrum（热门L2）
  CoinType.ARB.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ARB.name,
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum One",
      "miniName": "ARB",
      "unit":"ETH",
      "chainId": 42161,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ARB",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://arb1.arbitrum.io/rpc",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":42161,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 7. OP - Optimism（热门L2）
  CoinType.OP.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.OP.name,
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Optimism Ethereum.png",
      "name": "Optimism",
      "miniName": "OP",
      "unit":"ETH",
      "chainId": 10,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "OP",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.optimism.io",
      "service_test": "https://kovan.optimism.io/",
      "chainId_test": 69,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":10,
    "testnetChainID":69,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://kovan.optimism.io/",
        "testnetChainID":69,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 8. BASE - Base（Coinbase L2，热门）
  CoinType.BASE.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "mKey": "BASE",
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BASE.name,
      "icon": "https://astranet.app/static/base.png",
      "name": "Base",
      "miniName": "BASE",
      "unit":"ETH",
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.base.org",
      "service_test": "https://mainnet.base.org",
      "chainId": 8453,
      "chainId_test": 8453,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ERC20",
    },
    "mainnetChainID":8453,
    "testnetChainID":8453,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://mainnet.base.org",
        "testnetRPC":"https://mainnet.base.org",
        "testnetChainID":8453,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
      "0X833589FCD6EDB6E08F4C7C32D4F71B54BDA02913": <String,dynamic>{
        "mKey": "0X833589FCD6EDB6E08F4C7C32D4F71B54BDA02913",
        "blockchainType": BlockchainType.Ethereum.name,
        "coinType": CoinType.BASE.name,
        "icon": "https://api.astranet.app/market/v1/r/coinImage/USDC.png",
        "name": "USD Coin",
        "miniName": "USDC",
        "unit":"USDC",
        "decimals": 6,
        "balance":"0",
        "balance_test":"0",
        "coinPrice":0.0,
        "percentage":0.0,
        "isContract": true,
        "path": {
          "legacy":"m/44'/60'/0'/0/0",
        },
        "service": "https://mainnet.base.org",
        "service_test": "https://mainnet.base.org",
        "chainId": 8453,
        "chainId_test": 8453,
        "contract": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
        "contract_test": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
        "canEdit": true,
        "rules": "ERC20",
      },
    },
  },

  // 9. AVAX - Avalanche（热门公链）
  CoinType.AVAX.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.AVAX.name,
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Avalanche C-Chain.png",
      "name": "Avalanche C-Chain",
      "miniName": "AVAX",
      "unit":"AVAX",
      "chainId": 43114,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "AVAX",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://api.avax.network/ext/bc/C/rpc",
      "service_test": "https://api.avax-test.network/ext/bc/C/rpc",
      "chainId_test": 43113,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":43114,
    "testnetChainID":43113,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://api.avax-test.network/ext/bc/C/rpc",
        "testnetChainID":43113,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 10. MATIC - Polygon（热门L2/侧链）
  CoinType.MATIC.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.MATIC.name,
      "icon": "https://api-wallet.walletamaze.com/market/v1/r/coinImage/Polygon.png",
      "name": "Polygon",
      "miniName": "MATIC",
      "unit":"MATIC",
      "chainId": 137,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "MATIC",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://polygon-rpc.com/",
      "service_test": "https://matic-mumbai.chainstacklabs.com",
      "chainId_test": 80001,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":137,
    "testnetChainID":80001,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"https://matic-mumbai.chainstacklabs.com",
        "testnetChainID":80001,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 11. TON - The Open Network（热门，Telegram生态）
  CoinType.TON.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.TheOpenNetwork.name,
      "coinType": CoinType.TON.name,
      "icon": "https://cryptologos.cc/logos/toncoin-ton-logo.png",
      "name": "TON",
      "miniName": "TON",
      "unit":"TON",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "TON",
      "path": {
        "legacy":"m/44'/607'/0'",
      },
      "service": "https://toncenter.com/api/v2/jsonRPC",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "Jetton",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{}
      },
    ],
    "mainnets":<String,dynamic>{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 12. TRX - Tron（活跃用户多，USDT主要流通链）
  CoinType.TRX.name:<String,dynamic>{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":<String,dynamic>{
      "blockchainType": BlockchainType.Tron.name,
      "coinType": CoinType.TRX.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/TRON.png",
      "name": "Tron",
      "miniName": "TRX",
      "unit":"TRX",
      "chainId": 0,
      "decimals": 6,
      "balance":'0',
      "balance_test":'0',
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "TRX",
      "path": {
        "legacy":"m/44'/195'/0'/0/0",
      },
      "service": "https://api.trongrid.io/jsonrpc",
      "service_test": "https://nile.trongrid.io/jsonrpc",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "TRC20",
    },
    "mainnetWS":"https://api.trongrid.io",
    "mainnetRPC":"https://api.trongrid.io",
    "mainnetChainID":0,
    "testnetWS":"https://api.shasta.trongrid.io",
    "testnetRPC":"https://api.shasta.trongrid.io",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://api.shasta.trongrid.io",
        "testnetRPC":"https://api.shasta.trongrid.io",
        "testnetChainID":0,
        "testnetContract":<String,dynamic>{
        }
      },
    ],
    "mainnets":<String,dynamic>{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 13. XRP - Ripple（知名度高）
  CoinType.XRP.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ripple.name,
      "coinType": CoinType.XRP.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/XRP.png",
      "name": "Ripple",
      "miniName": "XRP",
      "unit":"XRP",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "XRP",
      "path": {
        "legacy":"m/44'/144'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XRP",
    },
    "mainnetWS":"https://rpc.tulip.tools/mainnet",
    "mainnetRPC":"https://rpc.tulip.tools/mainnet",
    "mainnetChainID":0,
    "testnetWS":"https://rpc.tulip.tools/mainnet",
    "testnetRPC":"https://rpc.tulip.tools/mainnet",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://rpc.tulip.tools/mainnet",
        "testnetRPC":"https://rpc.tulip.tools/mainnet",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 14. ATOM - Cosmos（跨链生态核心）
  CoinType.ATOM.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Cosmos.name,
      "coinType": CoinType.ATOM.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Cosmos Hub.png",
      "name": "Cosmos",
      "miniName": "ATOM",
      "unit":"ATOM",
      "chainId": "cosmoshub-4",
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ATOM",
      "path": {
        "legacy":"m/44'/118'/0'/0/0",
      },
      "service": "https://cosmos-lcd.quickapi.com/",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "ATOM",
    },
    "mainnetWS":"https://stargate.cosmos.network",
    "mainnetRPC":"https://stargate.cosmos.network",
    "mainnetChainID":0,
    "testnetWS":"https://stargate.cosmos.network",
    "testnetRPC":"https://stargate.cosmos.network",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"https://stargate.cosmos.network",
        "testnetRPC":"https://stargate.cosmos.network",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 15. DOT - Polkadot（知名跨链公链）
  CoinType.DOT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Polkadot.name,
      "coinType": CoinType.DOT.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Polkadot.png",
      "name": "Polkadot",
      "miniName": "DOT",
      "unit":"DOT",
      "chainId": 354,
      "decimals": 10,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "DOT",
      "path": {
        "legacy":"m/44'/354'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "DOT",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 16. FIL - Filecoin（存储公链）
  CoinType.FIL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Filecoin.name,
      "coinType": CoinType.FIL.name,
      "icon": "https://api.n42.ai/market/v1/r/coinImage/Filecoin.png",
      "name": "Filecoin",
      "miniName": "FIL",
      "unit":"FIL",
      "chainId": 461,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "FIL",
      "path": {
        "legacy":"m/44'/461'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "FIL",
    },
    "mainnetWS":"",
    "mainnetRPC":"",
    "mainnetChainID":0,
    "testnetWS":"",
    "testnetRPC":"",
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[
      {
        "testnetWS":"",
        "testnetRPC":"",
        "testnetChainID":0,
        "testnetContract":{
        }
      },
    ],
    "mainnets":{
    },
    "mainnetContract":{
    },
    "testnetContract":{
    },
  },

  // 17. SUI - Sui（Move语言公链，热门）
  CoinType.SUI.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Sui.name,
      "coinType": CoinType.SUI.name,
      "icon": "https://cryptologos.cc/logos/sui-sui-logo.png",
      "name": "Sui",
      "miniName": "SUI",
      "unit":"SUI",
      "chainId": 0,
      "decimals": 9,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SUI",
      "path": {
        "legacy":"m/44'/784'/0'/0'/0'",
      },
      "service": "https://fullnode.mainnet.sui.io",
      "service_test": "https://fullnode.testnet.sui.io",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "SUI",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://fullnode.testnet.sui.io","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 18. APT - Aptos（Move语言公链）
  CoinType.APT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Aptos.name,
      "coinType": CoinType.APT.name,
      "icon": "https://cryptologos.cc/logos/aptos-apt-logo.png",
      "name": "Aptos",
      "miniName": "APT",
      "unit":"APT",
      "chainId": 1,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "APT",
      "path": {
        "legacy":"m/44'/637'/0'/0'/0'",
      },
      "service": "https://fullnode.mainnet.aptoslabs.com",
      "service_test": "https://fullnode.testnet.aptoslabs.com",
      "chainId_test": 2,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "APT",
    },
    "mainnetChainID":1,
    "testnetChainID":2,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://fullnode.testnet.aptoslabs.com","testnetChainID":2,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 19. ALGO - Algorand
  CoinType.ALGO.name:{
    "showList":true,
    "isTest":false,
    "supportTest":true,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Algorand.name,
      "coinType": CoinType.ALGO.name,
      "icon": "https://cryptologos.cc/logos/algorand-algo-logo.png",
      "name": "Algorand",
      "miniName": "ALGO",
      "unit":"ALGO",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ALGO",
      "path": {
        "legacy":"m/44'/283'/0'/0'/0'",
      },
      "service": "https://mainnet-api.algonode.cloud",
      "service_test": "https://testnet-api.algonode.cloud",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ALGO",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://testnet-api.algonode.cloud","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 20. XTZ - Tezos
  CoinType.XTZ.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Tezos.name,
      "coinType": CoinType.XTZ.name,
      "icon": "https://cryptologos.cc/logos/tezos-xtz-logo.png",
      "name": "Tezos",
      "miniName": "XTZ",
      "unit":"XTZ",
      "chainId": 0,
      "decimals": 6,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "XTZ",
      "path": {
        "legacy":"m/44'/1729'/0'/0'",
      },
      "service": "https://mainnet.api.tez.ie",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "XTZ",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 21. LTC - Litecoin
  CoinType.LTC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"segwit",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.LTC.name,
      "icon": "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
      "name": "Litecoin",
      "miniName": "LTC",
      "unit":"LTC",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "LTC",
      "path": {
        "legacy":"m/44'/2'/0'/0/0",
        "segwit":"m/84'/2'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 22. DOGE - Dogecoin
  CoinType.DOGE.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Bitcoin.name,
      "coinType": CoinType.DOGE.name,
      "icon": "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
      "name": "Dogecoin",
      "miniName": "DOGE",
      "unit":"DOGE",
      "chainId": 0,
      "decimals": 8,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "DOGE",
      "path": {
        "legacy":"m/44'/3'/0'/0/0",
      },
      "service": "",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": false,
      "rules": "",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 23. ETC - Ethereum Classic
  CoinType.ETC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ETC.name,
      "icon": "https://cryptologos.cc/logos/ethereum-classic-etc-logo.png",
      "name": "Ethereum Classic",
      "miniName": "ETC",
      "unit":"ETC",
      "chainId": 61,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ETC",
      "path": {
        "legacy":"m/44'/61'/0'/0/0",
      },
      "service": "https://etc.rivet.link",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":61,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 24. FTM - Fantom
  CoinType.FTM.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.FTM.name,
      "icon": "https://cryptologos.cc/logos/fantom-ftm-logo.png",
      "name": "Fantom",
      "miniName": "FTM",
      "unit":"FTM",
      "chainId": 250,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "FTM",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.ftm.tools",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":250,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 25. CRO - Cronos
  CoinType.CRO.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.CRO.name,
      "icon": "https://cryptologos.cc/logos/cronos-cro-logo.png",
      "name": "Cronos",
      "miniName": "CRO",
      "unit":"CRO",
      "chainId": 25,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "CRO",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://evm.cronos.org",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":25,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 26. KLAY - Klaytn
  CoinType.KLAY.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.KLAY.name,
      "icon": "https://cryptologos.cc/logos/klaytn-klay-logo.png",
      "name": "Klaytn",
      "miniName": "KLAY",
      "unit":"KLAY",
      "chainId": 8217,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "KLAY",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://public-en-cypress.klaytn.net",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":8217,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 27. ZKSYNC - zkSync Era (热门L2)
  CoinType.ZKSYNC.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.ZKSYNC.name,
      "icon": "https://cryptologos.cc/logos/zksync-zk-logo.png",
      "name": "zkSync Era",
      "miniName": "ZK",
      "unit":"ETH",
      "chainId": 324,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ZKSYNC",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://mainnet.era.zksync.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":324,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 28. LINEA - Linea (热门L2)
  CoinType.LINEA.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.LINEA.name,
      "icon": "https://cryptologos.cc/logos/linea-linea-logo.png",
      "name": "Linea",
      "miniName": "LINEA",
      "unit":"ETH",
      "chainId": 59144,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "LINEA",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.linea.build",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":59144,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 29. SCROLL - Scroll (热门L2)
  CoinType.SCROLL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.SCROLL.name,
      "icon": "https://cryptologos.cc/logos/scroll-scr-logo.png",
      "name": "Scroll",
      "miniName": "SCROLL",
      "unit":"ETH",
      "chainId": 534352,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "SCROLL",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.scroll.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":534352,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 30. MNT - Mantle
  CoinType.MNT.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.MNT.name,
      "icon": "https://cryptologos.cc/logos/mantle-mnt-logo.png",
      "name": "Mantle",
      "miniName": "MNT",
      "unit":"MNT",
      "chainId": 5000,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "MNT",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.mantle.xyz",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":5000,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 31. BLAST - Blast
  CoinType.BLAST.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.BLAST.name,
      "icon": "https://cryptologos.cc/logos/blast-blast-logo.png",
      "name": "Blast",
      "miniName": "BLAST",
      "unit":"ETH",
      "chainId": 81457,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "BLAST",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.blast.io",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":81457,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 32. NEAR - Near Protocol
  CoinType.NEAR.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Near.name,
      "coinType": CoinType.NEAR.name,
      "icon": "https://cryptologos.cc/logos/near-protocol-near-logo.png",
      "name": "NEAR Protocol",
      "miniName": "NEAR",
      "unit":"NEAR",
      "chainId": 0,
      "decimals": 24,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "NEAR",
      "path": {
        "legacy":"m/44'/397'/0'",
      },
      "service": "https://rpc.mainnet.near.org",
      "service_test": "https://rpc.testnet.near.org",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "NEAR",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://rpc.testnet.near.org","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 33. ZIL - Zilliqa
  CoinType.ZIL.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Zilliqa.name,
      "coinType": CoinType.ZIL.name,
      "icon": "https://cryptologos.cc/logos/zilliqa-zil-logo.png",
      "name": "Zilliqa",
      "miniName": "ZIL",
      "unit":"ZIL",
      "chainId": 0,
      "decimals": 12,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "ZIL",
      "path": {
        "legacy":"m/44'/313'/0'/0'/0'",
      },
      "service": "https://api.zilliqa.com",
      "service_test": "https://dev-api.zilliqa.com",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ZIL",
    },
    "mainnetChainID":0,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"https://dev-api.zilliqa.com","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 34. GNOSIS - Gnosis Chain (原xDAI)
  CoinType.GNOSIS.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.GNOSIS.name,
      "icon": "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png",
      "name": "Gnosis Chain",
      "miniName": "xDAI",
      "unit":"xDAI",
      "chainId": 100,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "GNOSIS",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://rpc.gnosischain.com",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":100,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },

  // 35. NOVA - Arbitrum Nova
  CoinType.NOVA.name:{
    "showList":true,
    "isTest":false,
    "supportTest":false,
    "addrType":"legacy",
    "pathIndex":0,
    "pathList":[0],
    "baseInfo":{
      "blockchainType": BlockchainType.Ethereum.name,
      "coinType": CoinType.NOVA.name,
      "icon": "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
      "name": "Arbitrum Nova",
      "miniName": "NOVA",
      "unit":"ETH",
      "chainId": 42170,
      "decimals": 18,
      "balance":"0",
      "balance_test":"0",
      "coinPrice":0.0,
      "percentage":0.0,
      "isContract": false,
      "mKey": "NOVA",
      "path": {
        "legacy":"m/44'/60'/0'/0/0",
      },
      "service": "https://nova.arbitrum.io/rpc",
      "service_test": "",
      "chainId_test": 0,
      "contract": "",
      "contract_test": "",
      "canEdit": true,
      "rules": "ERC20",
    },
    "mainnetChainID":42170,
    "testnetChainID":0,
    "testnetIndex":0,
    "testnets":[{"testnetWS":"","testnetRPC":"","testnetChainID":0,"testnetContract":{}}],
    "mainnets":{},
    "mainnetContract":{},
    "testnetContract":{},
  },
};

//根据 index和默认path 返回新path
String getPathWithIndex(String path,int index){
  List<String> paths=path.split('/');
  if(paths.length>=4){
    int indexOf=paths[paths.length-1].lastIndexOf("'");
    String rPath="";
    for(int i=0;i<paths.length-1;i++){
      rPath+="${paths[i]}/";
    }
    if(indexOf==-1){
      rPath+="$index";
    }else{
      rPath+="$index'";
    }
    return rPath;
  }else{
    return path;
  }
}
Map<String,String>decimalMap={
  "0" :"1.0",
  '1' :"10.0",
  '2' :"100.0",
  '3' :"1000.0",
  '4' :"10000.0",
  '5' :"100000.0",
  '6' :"1000000.0",
  '7' :"10000000.0",
  '8' :"100000000.0",
  '9' :"1000000000.0",
  '10':"10000000000.0",
  '11':"100000000000.0",
  '12':"1000000000000.0",
  '13':"10000000000000.0",
  '14':"100000000000000.0",
  '15':"1000000000000000.0",
  '16':"10000000000000000.0",
  '17':"100000000000000000.0",
  '18':"1000000000000000000.0",
  '19':"10000000000000000000.0",
  '20':"100000000000000000000.0",
  '21':"1000000000000000000000.0",
  '22':"10000000000000000000000.0",
  '23':"100000000000000000000000.0",
  '24':"1000000000000000000000000.0",  // NEAR uses 24 decimals
};
Decimal toEther(String wei,int decimal) {
  int weiLength=wei.length;
  if(weiLength>decimal){
    String wei1=wei.substring(0,weiLength-decimal);
    String wei2="0.${wei.substring(weiLength-decimal)}";
    return Decimal.parse(wei1)+Decimal.parse(wei2);
  }else{
    // Safe access to decimalMap, dynamically calculate if not found
    String? divisor = decimalMap[decimal.toString()];
    if (divisor == null) {
      // Dynamically calculate the divisor for unsupported decimals
      divisor = BigInt.from(10).pow(decimal).toString() + ".0";
    }
    Decimal dd=(Decimal.parse(wei) / Decimal.parse(divisor)).toDecimal();
    return dd;
  }
}

double toGWei(String wei) {
  int l = wei.length;
  if (l <= 1) {
    return double.parse(wei);
  }

  if (l <= 9) {
    Decimal formatted= (Decimal.parse(wei) / Decimal.parse('1000000000')).toDecimal();
    return formatted.toDouble();
  } else {
    int fix = l - 9;
    String formatted ="${wei.substring(0, fix)}.${wei.substring(fix, l)}";
    return Decimal.parse(formatted).toDouble();
  }
}

BigInt ethToWeiString(String eth,int decimals) {
  List<String> list = eth.split('.');
  if (list.length > 2) {
    return BigInt.from(0);
  }
  BigInt prix = BigInt.parse(list[0]);
  if(decimals==18){
    EtherAmount a =
    EtherAmount.fromBigInt(EtherUnit.ether, prix);
    if (list.length == 1) {
      return a.getInWei;
    }
    int len = list[1].length;
    if(len>18){
      len=18;
    }
    int diff = 18 - len;
    BigInt bDiff = BigInt.parse(list[1]);
    BigInt n = bDiff * BigInt.from(10).pow(diff);
    return a.getInWei + n;
  }else{
    // Safe access to decimalMap, dynamically calculate if not found
    String? decStr = decimalMap[decimals.toString()];
    if (decStr == null) {
      decStr = BigInt.from(10).pow(decimals).toString() + ".0";
    }
    double dec= double.parse(decStr);
    Decimal rValue=Decimal.parse(eth)*Decimal.parse(dec.toString());
    return rValue.toBigInt();
  }
}
