import 'package:n42appv2/src/component/enums/coin_type.dart';

final Map<String, dynamic> chainDataPart4 = <String, dynamic>{
  CoinType.PLUME.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "PLUME",
      "icon": "https://cryptologos.cc/logos/plume-logo.png",
      "name": "Plume",
      "miniName": "PLUME",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "PLUME",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.plumenetwork.xyz",
      "service_test": "",
      "chainId": 98865,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 98865,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.POA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "POA",
      "icon": "https://cryptologos.cc/logos/poa-network-poa-logo.png",
      "name": "POA Network",
      "miniName": "POA",
      "unit": "POA",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "POA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://core.poa.network",
      "service_test": "",
      "chainId": 99,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 99,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.S.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "S",
      "icon": "https://cryptologos.cc/logos/sonic-s-logo.png",
      "name": "Sonic",
      "miniName": "S",
      "unit": "S",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "S",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.soniclabs.com",
      "service_test": "",
      "chainId": 146,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 146,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SAAKURU.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SAAKURU",
      "icon": "https://cryptologos.cc/logos/saakuru-logo.png",
      "name": "Saakuru",
      "miniName": "OAS",
      "unit": "OAS",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SAAKURU",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.saakuru.network",
      "service_test": "",
      "chainId": 7225878,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7225878,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.STRATO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "STRATO",
      "icon": "https://cryptologos.cc/logos/stratovm-logo.png",
      "name": "StratoVM",
      "miniName": "SVM",
      "unit": "BTC",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "STRATO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.stratovm.io",
      "service_test": "",
      "chainId": 93747,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 93747,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XDAI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "XDAI",
      "icon": "https://cryptologos.cc/logos/gnosis-gno-gno-logo.png",
      "name": "Gnosis Chain (xDai)",
      "miniName": "xDAI",
      "unit": "xDAI",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XDAI",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gnosischain.com",
      "service_test": "",
      "chainId": 100,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 100,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ZETA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ZETA",
      "icon": "https://cryptologos.cc/logos/zetachain-zeta-logo.png",
      "name": "ZetaChain",
      "miniName": "ZETA",
      "unit": "ZETA",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ZETA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://zetachain-evm.blockpi.network/v1/rpc/public",
      "service_test": "",
      "chainId": 7000,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 7000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.EDU.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "EDU",
      "icon": "https://cryptologos.cc/logos/open-campus-edu-logo.png",
      "name": "Open Campus Codex",
      "miniName": "EDU",
      "unit": "EDU",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "EDU",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.edu.evm.network",
      "service_test": "",
      "chainId": 656476,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 656476,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MOVE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MOVE",
      "icon": "https://cryptologos.cc/logos/movement-move-logo.png",
      "name": "Movement",
      "miniName": "MOVE",
      "unit": "MOVE",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MOVE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mevm.devnet.imola.movementlabs.xyz",
      "service_test": "",
      "chainId": 30732,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 30732,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Batch 9: Bitcoin-like chains
  CoinType.BCH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "BCH",
      "icon": "https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png",
      "name": "Bitcoin Cash",
      "miniName": "BCH",
      "unit": "bch",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BCH",
      "path": {
        "legacy": "m/44'/145'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.BTG.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "BTG",
      "icon": "https://cryptologos.cc/logos/bitcoin-gold-btg-logo.png",
      "name": "Bitcoin Gold",
      "miniName": "BTG",
      "unit": "btg",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BTG",
      "path": {
        "legacy": "m/44'/156'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DGB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DGB",
      "icon": "https://cryptologos.cc/logos/digibyte-dgb-logo.png",
      "name": "DigiByte",
      "miniName": "DGB",
      "unit": "dgb",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DGB",
      "path": {
        "segwit": "m/84'/20'/0'/0/0",
        "legacy": "m/44'/20'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MONA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "MONA",
      "icon": "https://cryptologos.cc/logos/monacoin-mona-logo.png",
      "name": "Monacoin",
      "miniName": "MONA",
      "unit": "mona",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MONA",
      "path": {
        "segwit": "m/84'/22'/0'/0/0",
        "legacy": "m/44'/22'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.RVN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "RVN",
      "icon": "https://cryptologos.cc/logos/ravencoin-rvn-logo.png",
      "name": "Ravencoin",
      "miniName": "RVN",
      "unit": "rvn",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "RVN",
      "path": {
        "legacy": "m/44'/175'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.VIA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "segwit",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "VIA",
      "icon": "https://cryptologos.cc/logos/viacoin-via-logo.png",
      "name": "Viacoin",
      "miniName": "VIA",
      "unit": "via",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "VIA",
      "path": {
        "segwit": "m/84'/14'/0'/0/0",
        "legacy": "m/44'/14'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DFI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Bitcoin",
      "coinType": "DFI",
      "icon": "https://cryptologos.cc/logos/defichain-dfi-logo.png",
      "name": "DeFiChain",
      "miniName": "DFI",
      "unit": "dfi",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DFI",
      "path": {
        "legacy": "m/44'/1129'/0'/0/0"
      },
      "service": "",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Batch 10: Non-EVM chains with TWC support
  CoinType.ALGO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Algorand",
      "coinType": "ALGO",
      "icon": "https://cryptologos.cc/logos/algorand-algo-logo.png",
      "name": "Algorand",
      "miniName": "ALGO",
      "unit": "ALGO",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ALGO",
      "path": {"legacy": "m/44'/283'/0'/0'/0'"},
      "service": "https://mainnet-api.algonode.cloud",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ASA"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.APT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Aptos",
      "coinType": "APT",
      "icon": "https://cryptologos.cc/logos/aptos-apt-logo.png",
      "name": "Aptos",
      "miniName": "APT",
      "unit": "APT",
      "decimals": 8,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "APT",
      "path": {"legacy": "m/44'/637'/0'/0'/0'"},
      "service": "https://fullnode.mainnet.aptoslabs.com/v1",
      "chainId": 1,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 1,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ATOM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Cosmos",
      "coinType": "ATOM",
      "icon": "https://cryptologos.cc/logos/cosmos-atom-logo.png",
      "name": "Cosmos",
      "miniName": "ATOM",
      "unit": "ATOM",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ATOM",
      "path": {"legacy": "m/44'/118'/0'/0/0"},
      "service": "https://cosmos-rest.publicnode.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.DOT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Polkadot",
      "coinType": "DOT",
      "icon": "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
      "name": "Polkadot",
      "miniName": "DOT",
      "unit": "DOT",
      "decimals": 10,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "DOT",
      "path": {"legacy": "m/44'/354'/0'/0'/0'"},
      "service": "https://rpc.polkadot.io",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KSM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Polkadot",
      "coinType": "KSM",
      "icon": "https://cryptologos.cc/logos/kusama-ksm-logo.png",
      "name": "Kusama",
      "miniName": "KSM",
      "unit": "KSM",
      "decimals": 12,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KSM",
      "path": {"legacy": "m/44'/434'/0'/0'/0'"},
      "service": "https://kusama-rpc.polkadot.io",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.FIL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Filecoin",
      "coinType": "FIL",
      "icon": "https://cryptologos.cc/logos/filecoin-fil-logo.png",
      "name": "Filecoin",
      "miniName": "FIL",
      "unit": "FIL",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "FIL",
      "path": {"legacy": "m/44'/461'/0'/0/0"},
      "service": "https://api.node.glif.io",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SUI.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Sui",
      "coinType": "SUI",
      "icon": "https://cryptologos.cc/logos/sui-sui-logo.png",
      "name": "Sui",
      "miniName": "SUI",
      "unit": "SUI",
      "decimals": 9,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SUI",
      "path": {"legacy": "m/44'/784'/0'/0'/0'"},
      "service": "https://fullnode.mainnet.sui.io",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "TheOpenNetwork",
      "coinType": "TON",
      "icon": "https://cryptologos.cc/logos/toncoin-ton-logo.png",
      "name": "TON",
      "miniName": "TON",
      "unit": "TON",
      "decimals": 9,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TON",
      "path": {"legacy": "m/44'/607'/0'"},
      "service": "https://toncenter.com/api/v2/jsonRPC",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "Jetton"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XRP.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ripple",
      "coinType": "XRP",
      "icon": "https://cryptologos.cc/logos/xrp-xrp-logo.png",
      "name": "XRP",
      "miniName": "XRP",
      "unit": "XRP",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XRP",
      "path": {"legacy": "m/44'/144'/0'/0/0"},
      "service": "https://xrplcluster.com",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": ""
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.XTZ.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Tezos",
      "coinType": "XTZ",
      "icon": "https://cryptologos.cc/logos/tezos-xtz-logo.png",
      "name": "Tezos",
      "miniName": "XTZ",
      "unit": "XTZ",
      "decimals": 6,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "XTZ",
      "path": {"legacy": "m/44'/1729'/0'/0'"},
      "service": "https://mainnet.api.tez.ie",
      "chainId": 0,
      "contract": "",
      "canEdit": true,
      "rules": "FA1.2"
    },
    "mainnetChainID": 0,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Batch 11: Remaining EVM chains
  CoinType.BOB.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "BOB",
      "icon": "https://cryptologos.cc/logos/bob-logo.png",
      "name": "BOB",
      "miniName": "BOB",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "BOB",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.gobob.xyz",
      "service_test": "",
      "chainId": 60808,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 60808,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.KATANA.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "KATANA",
      "icon": "https://cryptologos.cc/logos/ronin-ron-logo.png",
      "name": "Ronin Katana",
      "miniName": "RON",
      "unit": "RON",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "KATANA",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.roninchain.com/rpc",
      "service_test": "",
      "chainId": 2020,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2020,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.TEMPO.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "TEMPO",
      "icon": "https://cryptologos.cc/logos/tempo-logo.png",
      "name": "Tempo",
      "miniName": "TEMPO",
      "unit": "TEMPO",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "TEMPO",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.tempo.xyz",
      "service_test": "",
      "chainId": 698,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 698,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  //Phase 1: High priority new EVM chains
  CoinType.HYPE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "HYPE",
      "icon": "https://cryptologos.cc/logos/hyperliquid-hype-logo.png",
      "name": "Hyperliquid",
      "miniName": "HYPE",
      "unit": "HYPE",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "HYPE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.hyperliquid.xyz/evm",
      "service_test": "",
      "chainId": 998,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 998,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MON.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MON",
      "icon": "https://cryptologos.cc/logos/monad-mon-logo.png",
      "name": "Monad",
      "miniName": "MON",
      "unit": "MON",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MON",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.monad.xyz",
      "service_test": "",
      "chainId": 41454,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 41454,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.ABSTRACT.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "ABSTRACT",
      "icon": "https://cryptologos.cc/logos/abstract-logo.png",
      "name": "Abstract",
      "miniName": "ABS",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "ABSTRACT",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://api.mainnet.abs.xyz",
      "service_test": "",
      "chainId": 2741,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 2741,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.IP.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "IP",
      "icon": "https://cryptologos.cc/logos/story-protocol-ip-logo.png",
      "name": "Story Protocol",
      "miniName": "IP",
      "unit": "IP",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "IP",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.storyrpc.io",
      "service_test": "",
      "chainId": 1514,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1514,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.MEGAETH.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "MEGAETH",
      "icon": "https://cryptologos.cc/logos/megaeth-logo.png",
      "name": "MegaETH",
      "miniName": "MEGA",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "MEGAETH",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.megaeth.com",
      "service_test": "",
      "chainId": 6342,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 6342,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SONEIUM.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SONEIUM",
      "icon": "https://cryptologos.cc/logos/soneium-logo.png",
      "name": "Soneium",
      "miniName": "SON",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SONEIUM",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.soneium.org",
      "service_test": "",
      "chainId": 1868,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 1868,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.CORN.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "CORN",
      "icon": "https://cryptologos.cc/logos/corn-logo.png",
      "name": "Corn",
      "miniName": "CORN",
      "unit": "BTCN",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "CORN",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.corn-rpc.com",
      "service_test": "",
      "chainId": 21000000,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 21000000,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SHAPE.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SHAPE",
      "icon": "https://cryptologos.cc/logos/shape-logo.png",
      "name": "Shape",
      "miniName": "SHAPE",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SHAPE",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://mainnet.shape.network",
      "service_test": "",
      "chainId": 360,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 360,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.SUPERPOSITION.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "SUPERPOSITION",
      "icon": "https://cryptologos.cc/logos/superposition-logo.png",
      "name": "Superposition",
      "miniName": "SPN",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "SUPERPOSITION",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.superposition.io",
      "service_test": "",
      "chainId": 55244,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 55244,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.POLYNOMIAL.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "POLYNOMIAL",
      "icon": "https://cryptologos.cc/logos/polynomial-logo.png",
      "name": "Polynomial",
      "miniName": "POLY",
      "unit": "ETH",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "POLYNOMIAL",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.polynomial.fi",
      "service_test": "",
      "chainId": 8008,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 8008,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
  CoinType.LENSNETWORK.name: <String,dynamic>{
    "isTest": false,
    "supportTest": false,
    "addrType": "legacy",
    "pathIndex": 0,
    "pathList": [0],
    "baseInfo": <String,dynamic>{
      "blockchainType": "Ethereum",
      "coinType": "LENSNETWORK",
      "icon": "https://cryptologos.cc/logos/lens-protocol-lens-logo.png",
      "name": "Lens Network",
      "miniName": "LENS",
      "unit": "GHO",
      "decimals": 18,
      "balance": "0",
      "coinPrice": 0.0,
      "percentage": 0.0,
      "isContract": false,
      "mKey": "LENSNETWORK",
      "path": {"legacy": "m/44'/60'/0'/0/0"},
      "service": "https://rpc.lens.xyz",
      "service_test": "",
      "chainId": 37111,
      "chainId_test": 0,
      "contract": "",
      "canEdit": true,
      "rules": "ERC20"
    },
    "mainnetChainID": 37111,
    "testnetChainID": 0,
    "testnetIndex": 0,
    "testnets": [{"testnetWS": "", "testnetRPC": "", "testnetChainID": 0, "testnetContract": <String,dynamic>{}}],
    "mainnets": <String,dynamic>{},
    "mainnetContract": {},
    "testnetContract": {}
  },
};
