{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.reown-com",
    "module": "yttrium",
    "version": "0.10.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "yttrium-wcpay-0.10.60.aar",
          "url": "yttrium-wcpay-0.10.60.aar",
          "size": 4994538,
          "sha512": "c83dc01750e23f0d90597bce96e741ed81143fb3286f1adc8e0eb4db0d4ec7cf977523cb5217db14cd4f80cfb48b222b6cdbd002b725d8d95d9f501f812c339c",
          "sha256": "edf6908e5ec8c3e0b0ef2d45b47347c55ea84c96907fd952fadb84b038607303",
          "sha1": "0837363be7a839fb7aa5a97731b9350191b83275",
          "md5": "c8d487d24ca15b9b37fb0a28a592e71d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "yttrium-wcpay-0.10.60.aar",
          "url": "yttrium-wcpay-0.10.60.aar",
          "size": 4994538,
          "sha512": "c83dc01750e23f0d90597bce96e741ed81143fb3286f1adc8e0eb4db0d4ec7cf977523cb5217db14cd4f80cfb48b222b6cdbd002b725d8d95d9f501f812c339c",
          "sha256": "edf6908e5ec8c3e0b0ef2d45b47347c55ea84c96907fd952fadb84b038607303",
          "sha1": "0837363be7a839fb7aa5a97731b9350191b83275",
          "md5": "c8d487d24ca15b9b37fb0a28a592e71d"
        }
      ]
    }
  ]
}
